### ISSUE TITLE
Add language property to resource model

### ISSUE THREAD

**Issue by juliapampus** [FraunhoferISST/DataspaceConnector#114]
The IDS mapping puts the language property automatically (`IdsUtils::getAsResource`). We need to make this an editable attribute in the context of resource handling via the REST API.

**Comment by goekhanKahriman** [comment]
The resource creation in the config manager has a Language field to specify the language. Currently, however, the ResourceMetadata class has no Language attribute and is automatically set to English. Therefore, the input via the UI is not accepted.

**Comment by goekhanKahriman** [comment]
Please leave a comment in the following issue: https://github.com/FraunhoferISST/IDS-ConfigurationManager/issues/2  when this ToDO is done, so that the changes in the Configmanager will be followed up

**Comment by juliapampus** [comment]
Will come with issue #113.
