### ISSUE TITLE
Official Docker Images

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#119]
Hi, please provide an official docker build. There is one for version 3.2.1 but not for the current release v4.0.

**Comment by juliapampus** [comment]
Hi, do you mean the Image at https://github.com/orgs/FraunhoferISST/packages?repo_name=DataspaceConnector or the test setups at the release?

**Comment by sebplorenz** [comment]
I mean there is an image available at https://github.com/orgs/FraunhoferISST/packages?repo_name=DataspaceConnector 
for v3.2.1 but no image for the current release.

**Comment by juliapampus** [comment]
@brianjahnke is working in [branch 119](https://github.com/FraunhoferISST/DataspaceConnector/tree/119-offical-docker-image) to automate the Image building process and setting the configurations as volumes. For making things easier for all of us and all future releases. We provide a `Dockerfile` and a `docker-compose.yml` within this repository. The manual at the [wiki](https://github.com/FraunhoferISST/DataspaceConnector/wiki/Development#docker-setup) provides a detailed step-to-step guide. If it is urgent, please build the image yourself. We're working on it, I'll get back to you here.

**Comment by juliapampus** [comment]
https://github.com/FraunhoferISST/DataspaceConnector/packages/490191?version=4.0.1 @sebplorenz

**Comment by sebplorenz** [comment]
$ docker pull docker.pkg.github.com/fraunhoferisst/dataspaceconnector/dataspace-connector:4.0.1
Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.

This happens even if I successfully docker login to docker.pkg.github.com with my github credentials before.

**Comment by juliapampus** [comment]
This seems to be a problem with GitHub packages, unfortunately I can't help you with that.

**Comment by sebplorenz** [comment]
OK. Login to Github package registry works with token instead of password.
