### ISSUE TITLE
GET Self-Description?

### ISSUE THREAD

**Issue by jlangkau** [FraunhoferISST/DataspaceConnector#12]
Getting ones Self-Decription has to be done by POST-multipart. (Here with given message-type: https://github.com/International-Data-Spaces-Association/InformationModel/blob/1e6029c0a575381017c75280b69143822fa49e4a/taxonomies/Message.ttl#L69)

Here the line in current 'openapi.yaml':

https://github.com/FraunhoferISST/DataspaceConnector/blob/11681912102ca1f1446fe3666df8b44f3468b736/openapi.yaml#L174

**Comment by juliapampus** [comment]
Thanks for the hint. The self-description can already be retrieved by sending a DescriptionRequestMessage without a requested element via POST multipart. The GET endpoint was created for plugfest tests, because I noticed that other connectors offer this as well.

**Comment by juliapampus** [comment]
In my documentation and all my demos, I explain that the POST endpoint must be used for a correct self-description request. Should I move the GET endpoint to the admin API to only provide it for testing purpose?
