### ISSUE TITLE
Use proxy configuration in http requests

### ISSUE THREAD

**Issue by thkrebs** [FraunhoferISST/DataspaceConnector#136]
When resources/artifacts of type "http-get" are retrieved, the issued HTTP requests are not using the proxy setting defined in config.json.
Hence, if the connector is running behind a proxy, proxy settings need to configured on the command line when the connector is started which seems to be counterintuitive when having a proxy configuration available.

**Comment by juliapampus** [comment]
Should be closed with pull request #155 in the current dev branch (v4.1.0-SNAPSHOT).
