### ISSUE TITLE
latest version of the master: "Internal Server Error"

### ISSUE THREAD

**Issue by FabioDangelox** [FraunhoferISST/DataspaceConnector#137]
I use the latest version of the master branch of this Connector:
https://github.com/FraunhoferISST/DataspaceConnector

Before i start a Dockercontainer with the swagger ui on the Port 8084, i delete the proxy settings.
After this i start a Connector(Port 8084).
If i try to GET ​/admin​/api​/connector (Connector Self-description), i always recieve the following error:

{
"timestamp": "2021-02-01T14:41:28.497+0000",
"status": 500,
"error": "Internal Server Error",
"message": "could not deserialize; nested exception is org.hibernate.type.SerializationException: could not deserialize",
"path": "/admin/api/connector"
}

Can someone explain me how to fix this issue?

Thanks in advance.

Best regards,
Fabio D'Angelo

**Comment by juliapampus** [comment]
Hi, have you tried to clean and rebuild everything? This seems like a database error.

**Comment by FabioDangelox** [comment]
Thanks for your help, i will try to rebuild the container and i will also check the database settings.
