### ISSUE TITLE
Improve Documentation about Env Variables

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/DataspaceConnector#181]
It is handy to know where to find the possible environment variables. Non-Java-Developer will not know that you can set this Variables e.g. in the `docker-compose.yml`.

https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/30300a6368a7f7b313a16d779427d671f02cfa79/src/main/resources/application.properties#L1

**Comment by juliapampus** [comment]
Thanks for the issue. We will add hints to the Spring and Docker documentation to our wiki.
