### ISSUE TITLE
Unable to send resource UUID in API request using Python

### ISSUE THREAD

**Issue by Khamar-Uz-Zama** [FraunhoferISST/DataspaceConnector#190]
Hi,

I have setup a simple Producer-Consumer setup using IDS Connector and I am trying to exchange data using the Connector’s API in PYTHON. Using the API, I was able to create a resource at the Provider but I am facing an error while adding data to this resource. 

**Method 1:**
Code:
![image](https://user-images.githubusercontent.com/52586051/111316930-b0377c80-8689-11eb-8f6d-52a23ef21e5f.png)

Error:
![image](https://user-images.githubusercontent.com/52586051/111316991-bcbbd500-8689-11eb-8587-8a8f4a11a15a.png)

**Method 2:**
So I converted the resourceUUID which is of datatype String to UUID object and pass it as UUID object but I get another error.

resourceUUID as an UUID object:
![image](https://user-images.githubusercontent.com/52586051/111319225-c47c7900-868b-11eb-9137-615e1fea50b2.png)

Code:
![image](https://user-images.githubusercontent.com/52586051/111317001-c0e7f280-8689-11eb-92c6-417688ae29be.png)

Error:
![image](https://user-images.githubusercontent.com/52586051/111317015-c3e2e300-8689-11eb-83c6-6802cc92923b.png)

I have tried the solution from [StackOverflow](https://stackoverflow.com/a/48159596/14133428 ) but this gives same error as **Method 1:** 

I also had a look at the current and closed issues on Github but I could not find anything related. Is there any solution or short-term workaround for this?
It would be great if you could help me, thanks!

**Comment by ronjaquensel** [comment]
Hi,

in your first method, it looks like you're setting both the resource ID and the data string as request parameters, meaning they're appended to the URL. The resource ID is a path variable in the URL, so it has to be substituted instead of appended. The URL when calling this endpoint should look like */admin/api/resources/a4212311-86e4-40b3-ace3-ef29cd687cf9/data?data=someDataString*. I hope this solves the issue.

**Comment by Khamar-Uz-Zama** [comment]
Hi ronjaquensel ,
Thank you very much, that resolved the issue.
