### ISSUE TITLE
OAS operation POST /admin/api/resources/resource

### ISSUE THREAD

**Issue by simonpfeifhofer** [FraunhoferISST/DataspaceConnector#195]
Operation POST /admin/api/resources/resource should return a string however it returns a "plain" Guid. 
The quotation marks are missing.

It causes issues using default-deserialization implementations because it's not a valid JSON-string.

**Comment by juliapampus** [comment]
Hi, thanks for the feedback! We are aware of this fact. Fixed in v5.
