### ISSUE TITLE
The external REST API call does not work anymore in the latest version

### ISSUE THREAD

**Issue by NadiaFerchichi** [FraunhoferISST/DataspaceConnector#199]
These are the steps that i followed:

As a provider :
1- I created a resource.
2- I created a representation where i setup a connection to an external REST API.

And then, as a consumer:
3- I sent a resource description request to get the validation key.
4- I sent an artifact request to retrieve data.

But I received an error message "REJECTION: Something went wrong." with a code error 500.

I tested it with a representation connected to an external REST API with fix parameters (which does work with the version 3.2.0).
And also I tried it with a parametrized REST API call by following instructions described in the readme file of the framework.
But, in both cases, i received the same error message "REJECTION: Something went wrong."

**Comment by juliapampus** [comment]
From v3 to v4, we integrated the policy negotiation. The rejection message indicates that the http communication worked, but the ids request itself has been invalid. You could either turn off the contract negotation, or try to do it with a call `/contract` between the description request and artifact request.

**Comment by NadiaFerchichi** [comment]
> From v3 to v4, we integrated the policy negotiation. The rejection message indicates that the http communication worked, but the ids request itself has been invalid. You could either turn off the contract negotation, or try to do it with a call `/contract` between the description request and artifact request.

Thank you for your quick reply. I will try it, and i will keep you updated.

**Comment by NadiaFerchichi** [comment]
> From v3 to v4, we integrated the policy negotiation. The rejection message indicates that the http communication worked, but the ids request itself has been invalid. You could either turn off the contract negotation, or try to do it with a call `/contract` between the description request and artifact request.

I turned off the contract negotiation, but i got the same error message "REJECTION: Something went wrong."
Also, i tried the `/contract` call and provided the ids of the `contractOffer` in the body request but i received the error message "Failed to build contract request."

When i turned off the negotiation contract and tried to retrieve data, this is what i got in the log:
```{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:RejectionMessage",
  "@id" : "https://w3id.org/idsa/autogen/rejectionMessage/f2cb536e-b2da-42e3-8e52-d666dfe0ae98",
  "ids:rejectionReason" : {
    "@id" : "idsc:INTERNAL_RECIPIENT_ERROR"
  },
  "ids:modelVersion" : "4.0.0",
  "ids:issued" : {
    "@value" : "2021-03-26T16:38:46.630Z",
    "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
  },
  "ids:issuerConnector" : {
    "@id" : "https://w3id.org/idsa/autogen/baseConnector/7b934432-a85e-41c5-9f65-669219dde4ea"
  },
  "ids:securityToken" : {
    "@type" : "ids:DynamicAttributeToken",
    "@id" : "https://w3id.org/idsa/autogen/dynamicAttributeToken/2e323aa6-b962-469a-ae20-8c11f2c95e39",
    "ids:tokenValue" : "rejected!",
    "ids:tokenFormat" : {
      "@id" : "idsc:JWT"
    }
  },
  "ids:senderAgent" : {
    "@id" : "https://w3id.org/idsa/autogen/baseConnector/7b934432-a85e-41c5-9f65-669219dde4ea"
  },
  "ids:correlationMessage" : {
    "@id" : "https://INVALID"
  }
}
--q```

**Comment by juliapampus** [comment]
Sorry for not responding to this. Has the problem been solved in the meantime? I would generally recommend using one of the latest versions. Either v4.3.1 or v5.x.x
