### ISSUE TITLE
Provide ARM compatible Docker Images

### ISSUE THREAD

**Issue by juliapampus** [FraunhoferISST/DataspaceConnector#2]
"For our Supply Chain Execution Project, I want to use the IDS Connector on an ARM based Raspbery Pi 4 B+ 4GB with Raspbian 32 Bit. I can't use the provided docker images. It would be good to provide some ARM images in the future."

**Comment by brianjahnke** [comment]
The current project does not plan (at the moment) to prebuild arm docker images. If you need one please download the repo and build it yourself.
