### ISSUE TITLE
Daps token error messages when using wrong contract id

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#202]
When doing an Artifact Request I saw the following DSC error logs:
```
de.fraunhofer.isst.ids.framework.daps.DapsValidator - Could not parse incoming JWT/DAT!
de.fraunhofer.isst.ids.framework.daps.DapsValidator - Daps token of response could not be pased!
de.fraunhofer.isst.ids.framework.communication.http.IDSHttpServiceImpl - DAT of incoming response is not valid!
```
I found out that changing the transferContract uri in the Artifact Request fixes this error. When I switch back to the previously used transferContract uri this error appears again.

If the transferContract uri is wrong then there should be a message indicating this and not a Daps validation error.

**Comment by juliapampus** [comment]
Thanks for the issue. I don't see any correlation between transferContract and DAT for now. Nevertheless, we will test this for v5.
