### ISSUE TITLE
Transfer Contract URI can be used by multiple consumer DSCs

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#203]
If a consumer DSC requests a transfer contract from a producer DSC then the resulting transferContract URI can be used in other consumer DSCs as well. Even if the other consumer DSCs have different certificates. The other DSCs do not need to negotiate a contract if they are using the known transferContract URI of another client.
Since the negotiated transfer contract must be unique between a producer and a consumer, reusing it should not be possible.

**Comment by juliapampus** [comment]
Thank for the issue. That's a good hint, we put that on our todo list for the new version.
