### ISSUE TITLE
Running into compilation errors from (inclusive) TAG v4.0.0 onwards

### ISSUE THREAD

**Issue by edgardmarx** [FraunhoferISST/DataspaceConnector#208]
Hello,

I am facing some compilation errors from Tag 4.0.0 (inclusive) ahead.
The compilation problem is being generated from apparently removed ResourceMetadata inner class methods such as `getlicense` and `getVersion`.
Is there something that I can do to solve this issue?
Am I doing something wrong?

**Comment by juliapampus** [comment]
Thanks for the issue. Looks like the problem is caused by Lombok. We do not support old version, please try the latest version v4.3.1.
