### ISSUE TITLE
Compilation error on TAG v3.2.1

### ISSUE THREAD

**Issue by edgardmarx** [FraunhoferISST/DataspaceConnector#209]
- Missing Class `de.fraunhofer.isst.dataspaceconnector.controller.ResourceService`
- Missing entire package `de.fraunhofer.isst.dataspaceconnector.exceptions`
- Wrong import references to package `de.fraunhofer.isst.dataspaceconnector.services.resources instead` of `de.fraunhofer.isst.dataspaceconnector.services.resource`

**Comment by juliapampus** [comment]
Thanks for the issue. Looks like the problem might be due to your local setup, build tool, cache etc? We do not support old version, please try the latest version v4.3.1.
