### ISSUE TITLE
Additional hardening: Deactivation of features / debug interfaces

### ISSUE THREAD

**Issue by oxisto** [FraunhoferISST/DataspaceConnector#217]
It seems that by default, a lot of debug interfaces are activated and need to be turned off in a more "trusted" profile:

- Spring Boot Live Reload listening on port 3xxx introduced by `spring-boot-devtools`
- The H2 database admin interfaces at `/database`
- Spring Boot Actuator running on `/actuator`

**Comment by brianjahnke** [comment]
- Spring Boot Dev Tools are by default disabled when running 'java -jar app.jar' which the dataspace connector does in containers.
- Actuators are deactivated by default.

**Comment by oxisto** [comment]
> * Spring Boot Dev Tools are by default disabled when running 'java -jar app.jar' which the dataspace connector does in containers.

Good point

> * Actuators are deactivated by default.

So, to understand you correctly: The actuator interface itself is activated but not "actuator endpoints" are enabled, correct?

**Comment by brianjahnke** [comment]
The actuator dependency is loaded but all actuators are disabled. If you turn on one actuactor, you will also have to allow exposing an endpoint for this actuator. In contrast to the default spring actuactor behaviour: When turning on one endpoint, only this one endpoint will be turned on and not all other "default" actuators.

Also in v5 /database and /actuactor can only be accessed by people with the ADMIN role.
