### ISSUE TITLE
Fetching an Artifact is yielding "This code should not have been reached" in the DSC logs (version 4.0.0)

### ISSUE THREAD

**Issue by HariCazorla** [FraunhoferISST/DataspaceConnector#237]
Fetch a resource artifact using the REST endpoint - Backend: Resource data handling "/admin/api/resources/{resource-id}/data" the response is "Something went wrong". And in the DSC logs, there is an error message "This code should not have been reached". This is strange behavior and a proper error message is required.

1.  Host a JSON file on the Nginx server. Try to fetch the data from the URL http://localhost:9000/geojson/sample.json and also the curl command. It works as expected.
2. I have registered this new resource in my provider DSC.
3. I can fetch the metadata successfully using the Get Resource REST API.
4. From the provider DSC REST endpoint - Backend: Resource data handling "/admin/api/resources/{resource-id}/data" API fails to display the JSON contents. Rather it fails with the "Something is wrong" error message.
5. DSC logs have the following lines “failed to send http-get request”, “This code should not have been reached”, “resource could not be found”. Even though the resource is registered successfully.

A clear and concise error message should be logged.

![image](https://user-images.githubusercontent.com/17410351/117346454-0c5b9780-aea8-11eb-9bd6-255b077e27b8.png)

 - OS: Ubuntu (Windows WSL 2)
 - Browser [chrome]
 - Version [4.0.0]

**Comment by juliapampus** [comment]
Thanks for the issue! Could you please try the newest version v4.3.1? Let us know, if the error still comes up.

**Comment by HariCazorla** [comment]
Found the solution to this issue, the artifact was registered with URL  http://localhost:9000/geojson/sample.json instead of the  http://nginx:9000/geojson/sample.json. So DSC was not able to fetch from it. However, a concrete log message would've helped to debug it more quickly. I will try if it is seen in v4.3.1 and let you know.

**Comment by brianjahnke** [comment]
Hi,
since the problem seems to be resolved, we will close this issue.
