### ISSUE TITLE
Dataspace Connector V5 Backend API issue

### ISSUE THREAD

**Issue by aitorcelaya** [FraunhoferISST/DataspaceConnector#244]
Cloned the the version 5 of the Dataspace Connector and followed the standard deployment explained in the wiki tab.

Followed the Maven Build steps and the connector is successfully running. The connector is available at https://localhost:8080 as expected.

In the Backend API, I am able to access https://localhost:8000/v3/api-docs, but I am **NOT** able to access https://localhost:8080/admin/api or https://localhost:8080/admin/database.

I get the following in the terminal when accessing https://localhost:8080/admin/api:
![image](https://user-images.githubusercontent.com/82808687/117637113-cb9e9f80-b181-11eb-80a3-d7249b427625.png)

OS: Ubuntu
Browser: Firefox
Version: 88.0

**Comment by brianjahnke** [comment]
In v5 you need to access https://localhost:8080/api for the api entrypoint and https://localhost:8080/api/docs for swagger.

**Comment by sebplorenz** [comment]
After figuring out the new endpoints, I'm not able to create a resource with a corresponding artifact using the new API.
Is there an explaination available like https://github.com/International-Data-Spaces-Association/DataspaceConnector/wiki/ids-communication-guide but with the new API?

**Comment by HeinrichPet** [comment]
@sebplorenz You can find the new API description here: [https://international-data-spaces-association.github.io/DataspaceConnector/](https://international-data-spaces-association.github.io/DataspaceConnector/)
