### ISSUE TITLE
Connector acting as both a consumer and provider of data

### ISSUE THREAD

**Issue by musi00** [FraunhoferISST/DataspaceConnector#247]
It seems any data consumed by a connector cannot be offered to other connectors.  A scenario such as provider-->consumer1-->consumer2 where consumer2 can only communicate with consumer1 but not the provider.  Therefore it must get the data from consumer1.  In addition, consumer 1 can only keep the data as long as the usage policy allows it.  For example, if data usage is restricted by a duration, consumer 1 must delete the data and can longer provide the data to other connectors.

**Describe the solution you'd like**
1.  Consumer 1 can request data from provider in a way that tells the provider it will share the data with others (i.e it asks to become a provider).
2.  Consumer 1 must delete the data according to usage policy and therefore seize to become a provider of the data.

**Comment by brianjahnke** [comment]
This is already possible. You can create a new offered resource with the consumed data as artifact. The underlying contract for consuming is still enforced.
