### ISSUE TITLE
Artifact accessURL broken when stored in Connector

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#266]
I cannot query my artifact data because the access URL of the artifact description is changed when it is saved to the DSC database.

Using DSC v5 from dev branch I create an artifact:

```
curl -X 'PUT' \
  'http://localhost:8080/api/artifacts/7862747a-24d1-465e-9375-ce66700c70f6' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "title": "DWD Artifact",
  "accessUrl": "https://maps.dwd.de/geoserver/dwd/ows/?service=WFS&version=1.0.0&request=GetFeature&typeName=dwd%3AWarnungen_Gemeinden&outputFormat=application%2Fjson&download=true"
}'
```
When I query the artifact, I'm getting the following error:

```
2021-05-19T13:15:18,574 [http-nio-8080-exec-8] WARN - Could not connect to data source. [exception=(Unexpected code Response{protocol=http/1.1, code=404, message=Not Found, 
url=https://maps.dwd.de/geoserver/dwd/ows/%2F**?service=WFS&version=1.0.0&request=GetFeature&typeName=dwd%3AWarnungen_Gemeinden&outputFormat=application%2Fjson&download=true&download=true} 
With Body: <!DOCTYPE html>\r\n<html style="" xml:lang="de" lang="de">\r\n  <head>\r\n    <meta http-equiv="content-type" content="text/html; charset=UTF-8">\r\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\r\n    <meta charset="utf-8">\r\n    <meta name="viewport" content="minimum-scale=0.25, maximum-scale=5.0, initial-scale=1.0">\r\n    <title>Wetter- und Klimainformationen f&uuml;r Premiumkunden - Deutscher Wetterdienst - Fehlerseite</title>\r\n    <meta name="description"
...
```
As can be seen in the warning message the URL is different than the one I used to create the artifact. There is an extra %2F** before the parameters begin. This is why the DWD service responds with a 404 and the data cannot be retrieved.

I also tried to use this URL
https://maps.dwd.de/geoserver/dwd/ows

Then the error message is:
```
WARN - Could not connect to data source. [exception=(Unexpected code Response{protocol=http/1.1, code=404, message=Not Found, url=https://maps.dwd.de/geoserver/dwd/ows/%2F**} 
```

**Comment by brianjahnke** [comment]
Hi,

i have tried the first and the second provided url on the provider site and have no problem receiving data. I have looked into the stored url and the url used to send the request and they are identically to the provided one.

Can you please further describe your setup?

**Comment by sebplorenz** [comment]
Some update: I just realized, that the consumer can download the artifact when the contract is requested:
```
curl -X 'POST' \
  'http://localhost:8082/api/ids/contract?recipient=http%3A%2F%2F172.17.0.1%3A8080%2Fapi%2Fids%2Fdata&resourceIds=http%3A%2F%2F172.17.0.1%3A8080%2Fapi%2Foffers%2F71a9d3cd-7088-4424-ae7c-162073abf5f2&artifactIds=http%3A%2F%2F172.17.0.1%3A8080%2Fapi%2Fartifacts%2Fb5d143e3-80f5-4b52-bf1c-c7839ba484b1&download=true' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '[ {
        "@type" : "ids:Permission",
        "@id" : "http://localhost:8080/api/rules/5041c3e5-4933-419d-87d9-474b98ced678",
        "ids:description" : [ {
          "@value" : "provide-access",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:title" : [ {
          "@value" : "Example Usage Policy",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:action" : [ {
          "@id" : "idsc:USE"
        }],
        "ids:target" : "http://172.17.0.1:8080/api/artifacts/b5d143e3-80f5-4b52-bf1c-c7839ba484b1"
} ]'
```
The consumer can then consume the locally stored artifact data. 
However, if the consumer tries to download the artifact from the provider to then consume it:
```
curl -X 'GET' \
  'http://localhost:8082/api/artifacts/fbafcdb1-e516-4e6e-a504-ff5a17dbc989/data/**?download=true&agreementUri=http%3A%2F%2F172.17.0.1%3A8080%2Fapi%2Fagreements%2F9954899e-1348-48bb-a8c0-442fa3316c58' \
  -H 'accept: */*'
```
The error message is raised since the provider tries to fetch the data from the backend service but uses broken URL from its database.

**Comment by sebplorenz** [comment]
The script to create the resource on the provider side can be found here: https://gist.github.com/sebplorenz/d9fadc2b5dc72b9bef73ffe6a15dcfe0

**Comment by sebplorenz** [comment]
The problem is here https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/dc293bd3e761611d374bbb3dbc27cd520b6ea0a3/src/main/java/io/dataspaceconnector/services/HttpService.java#L160
The query input at this point is "/**" and it is appended to the backend service URL (the artifact URL pointing to DWD in the example above). How can I prevent this?

**Comment by brianjahnke** [comment]
I believe the problem only occurs when using the Swagger UI since the path in the Swagger UI is `/data/**`.
