### ISSUE TITLE
Readme mentions files that don't exist

### ISSUE THREAD

**Issue by hylkevds** [FraunhoferISST/DataspaceConnector#28]
The readme mentions two zip files that seem to be missing: java-setup.zip and docker-setup.zip
This makes it impossible to follow the "Getting Started" chapter

**Comment by mspiekermann** [comment]
The two test setups and the mentioned files _java-setup.zip_ and _docker-setup.zip_  are placed at the corresponding release. See "Getting started" section for the link or follow https://github.com/FraunhoferISST/DataspaceConnector/releases directly.
