### ISSUE TITLE
Cannot build DSC v.5.0.2 via Maven

### ISSUE THREAD

**Issue by martinHska** [FraunhoferISST/DataspaceConnector#290]
Hello there, 

while trying to build the DSC v5.0.2 locally via Maven I am receiving the BUILD FAILURE below. Building worked perfectly fine with the connectors v4.3.1 and v5.0.0. Find attached the dump files. 

OS: windows 10
mvn version: 3.8.1
java version: 13.0.2

"""
[ERROR] Failures:
[ERROR]   HttpTraceFilterTest.doFilterInternal_validRequest_captureRequest:106 expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 1022, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:49 min
[INFO] Finished at: 2021-05-26T14:55:06+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project dataspaceconnector: There are test failures.
[ERROR]
[ERROR] Please refer to K:\DataspaceConnector-5.0.2\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
""

[2021-05-26T15-10-17_721.dumpstream.txt](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/6546943/2021-05-26T15-10-17_721.dumpstream.txt)
[2021-05-26T15-10-17_721-jvmRun1.dump.txt](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/6546945/2021-05-26T15-10-17_721-jvmRun1.dump.txt)

Thanks a lot!

Best 
Martin

**Comment by ronjaquensel** [comment]
Hi Martin,

I just tried building version 5.0.2 locally and all tests passed. Also we execute all tests against different Java versions on three different OS before each merge. 

Does the problem persist after invalidating the Maven cache? If you're using Windows with OpenJDK, the OpenJDK might not terminate correctly, so it might have to be killed manually before trying to build the project.

Best regards,
Ronja

**Comment by martinHska** [comment]
Thank your, Ronja. Clearing the cache helped! Problem solved.
