### ISSUE TITLE
Integration of the IDS-Messaging-Services into the DSC

### ISSUE THREAD

**Issue by renebrinkhege** [FraunhoferISST/DataspaceConnector#294]
The [IDS-Connector-Framework](https://github.com/International-Data-Spaces-Association/IDS-Connector-Framework) shall be replaced by the [IDS-Messaging-Services](https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services).

**Comment by juliapampus** [comment]
Closed by #306

**Comment by juliapampus** [comment]
Closed by #306
