### ISSUE TITLE
Scripts for automatically setting up provider and consumer fail on certain json inputs for creating a contract

### ISSUE THREAD

**Issue by PaulThomas42** [FraunhoferISST/DataspaceConnector#296]
**Describe the bug**
As the script needs two connectors, there have been set up 2 different instances of a DSC on port 8080 and 8081 respectively.
When running the provided script provider_consumer_single_artifact_single_policy.py there seem to be some issues regarding the input of the create_contract() method. When providing the create_contract() method with additional fields besides the title of the contract this will result in the contract not beeing found when performing a contract request in the later stages of the script. 
If i just add the field "title":"Sample title" this works just fine.

**To Reproduce**
1. Do not change anything in the script besides adding: 
```
"consumer": "TEST-Consumer",
"provider": "TEST-Provider",
"title": "Sample Contract"
```
to the json part inside the create_contract() method.
2. If you run the script now this should result in following Message:
```
('b\'{"reason":{"properties":null,"@id":"idsc:NOT_FOUND"},"payload":"Could not '
 'find any matching contract offers for your '
 'request.","type":"de.fraunhofer.iais.eis.RejectionMessageImpl"}\'')
```

**Expected behavior**
Initiating the contract agreement and succesfully sending a contract request.

**Comment by ronjaquensel** [comment]
Hi,

I could reproduce this behaviour. The problem here is the line 
```
"consumer": "TEST-Consumer"
```
When a consumer is specified when creating a contract offer, that offer will only be available for a consumer with the same connector ID. Since "TEST-Consumer" is not a connector ID, the contract offer is not found when making the request. If you set the consumer's connector ID in the field, e.g.
```
"consumer": "https://w3id.org/idsa/autogen/baseConnector/7b934432-a85e-41c5-9f65-669219dde4ea"
```
the request should succeed.
