### ISSUE TITLE
Test sendDescriptionRequestMessage_validInput_() fails

### ISSUE THREAD

**Issue by thebe14** [FraunhoferISST/DataspaceConnector#325]
**Describe the bug**
The test sendDescriptionRequestMessage_validInput_() fails.

**To Reproduce**
1. Create and register two certificates as described under 1) here: https://daps.euh4d.dataspac.es/#dataweek
2. Configure connector as described under 2) in the above link, but most important set ids:connectorDeployMode to idsc:PRODUCTIVE_DEPLOYMENT
3. Build locally using Maven

Problem 1: Close to 200 tests fail at this point

4. Edit file /src/test/resources/application.properties with the same values as in step 2 (update configuration.keyStorePassword, configuration.trustStorePassword, server.ssl.key-store, server.ssl.key-store-password)
5. Build locally using Maven

Problem 2: Now all test pass except sendDescriptionRequestMessage_validInput_()

**Expected behavior**
All tests should pass.
Nice to have would be to not have to repeat the configuration in two places, it is hard to keep in sync.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Java 11

**Additional context**
NA

**Comment by brianjahnke** [comment]
Hi,

Regarding Problem 2: We are aware that this test fails. It will be addressed. 
Thank you for pointing it out!
