### ISSUE TITLE
Description does not match the function implementation

### ISSUE THREAD

**Issue by tejmann** [FraunhoferISST/DataspaceConnector#326]
**Describe the bug**
In the method checkDate in RuleUtils.java, description tells the method should return True if current date is later than target date but in the application we put a NOT in front of return statement. The method implementation is opposite to the description. Not sure if it is a bug or the description is wrong but if it is a bug this changes the logic of how data is deleted. 
![method](https://user-images.githubusercontent.com/46450421/121423826-aea2eb00-c93e-11eb-9d94-fd2ae3e6251b.png)

**To Reproduce**
1.Go to RuleUtils.java class, checkDate method. See error

**Expected behavior**
Not sure if this is just a error in the description or error in application as this changes the logic data deletion logic.

**Comment by brianjahnke** [comment]
Hi,

i had a quick look over the function and i agree that the documentation does not match the behaviour. Also the function seems to only be filled with DateTime.now() on the first parameter, so that could be dropped?
From the perspective of the data deletion logic, i believe the result is always inverted (its used only in two places)

**Comment by tejmann** [comment]
Hi,
So based on this logic we check all agreements every 60 seconds and delete the data if it has Delete post-duty until the time of deletion rather than after time of deletion. Shouldn't the expected behavior of the rule be it deletes the data after the deletion time just once?

**Comment by brianjahnke** [comment]
Yes, it should be. It will need to be fixed.

**Comment by tejmann** [comment]
Hi, even in the new implementation we are now deleting data (setting value to a null input stream) every 60 seconds from the date of deletion till **forever** which does not seem efficient .We are also not changing  `deleted = true`  anywhere for the artifact, and hence even after deletion we get the value in Deleted column of the artifact to be False in the database. Shouldn't we check if it has been already been deleted or not and then delete it depending on the result ? Currently we would be calling deletion logic on every artifact that has delete rule and it's time has expired over and over every 60 secs which seems unnecessary.
