### ISSUE TITLE
Add default policy

### ISSUE THREAD

**Issue by Apollo3zehn** [FraunhoferISST/DataspaceConnector#33]
Creating a new resource in swagger GUI with the default settings creates a resource without default policy. This leads to `Metadata could not be saved: Cannot invoke "de.fraunhofer.iais.eis.ContractOffer.toRdf()" because the return value of "java.util.ArrayList.get(int)" is null` when requesting that resource at the `admin/api/request/description` endpoint.

**Comment by juliapampus** [comment]
@Apollo3zehn Changes were added to the dev branch with pull request #36.
