### ISSUE TITLE
functions lacking on the API

### ISSUE THREAD

**Issue by jmartinezsqs** [FraunhoferISST/DataspaceConnector#331]
**Describe the bug**
The connector API is lacking a couple of functions to completely operate it. The functions missing are  `POST /api/requests` , `POST /api/agreements` and `PUT /api/agreements`,which makes it difficult to validate api's functionalities.

**Comment by brianjahnke** [comment]
Hi, 

you cannot create agreements via POST. They are the result of an ids contract negotiation. Please take a look at the [communication guide step 3](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/Consumer) in the documentation.

POST requested resources and PUT agreements do not exist for the same reason.
