### ISSUE TITLE
Completed offered resource not showing on the IDS self-decription

### ISSUE THREAD

**Issue by jmartinezsqs** [FraunhoferISST/DataspaceConnector#332]
**Describe the bug**
When creating an offered resource and completing it as the documentation says, the created resource doesn't appear in the `localhost:8080/` 

**To Reproduce**
1. Create via de api an offer, a catalog, a contract, a representation and an artifact
2. Link all of them so the offer is completed
3. Call the `GET /`
4. Te output doesn't contain the offered catalog

**Expected behavior**
When all the components are created they should appear in the IDS self-decription as said in the documentation.

**Comment by brianjahnke** [comment]
Hi,

under `/` you will find the public self description of the connector. For the complete self description containing the catalogs please call `api/connector`.

**Comment by jmartinezsqs** [comment]
Thanks for the help i've found it
