### ISSUE TITLE
Result of a sonarqube analysis on the code

### ISSUE THREAD

**Issue by jmartinezsqs** [FraunhoferISST/DataspaceConnector#340]
**Describe the bug**
I've run the sonarqube software to scan the code of the dataspace connector. It came up with some faults and some possible bugs. I attach the result od the analyse with a couple of photos. If it's needed any further infromation don't hesitate on contacting.

**Additional context**

![Captura](https://user-images.githubusercontent.com/82801379/121684044-7cb89280-cabe-11eb-818c-ed8544257357.PNG)
![overview](https://user-images.githubusercontent.com/82801379/121684048-7de9bf80-cabe-11eb-9f10-4cea735c7b80.PNG)
![overview2](https://user-images.githubusercontent.com/82801379/121684049-7de9bf80-cabe-11eb-92ca-04b641b18e3b.PNG)
![security hotspots](https://user-images.githubusercontent.com/82801379/121684051-7e825600-cabe-11eb-80a5-0f29f9f4b24e.PNG)

**Comment by brianjahnke** [comment]
Hi,

thank you very much for your interest in the DSC and sharing information with us.

FYI: When you run `mvn verify site -Prelease` our build system will also perform code and security analysis and generate a project report!
