### ISSUE TITLE
"INVALID_TOKEN": Fail connection with DAPS

### ISSUE THREAD

**Issue by narcaldas** [FraunhoferISST/DataspaceConnector#365]
**Describe the bug**
I was digging into the logs of the Connector and I noticed that the following message:
"Certificate ot the Connector is missing aki/ski extensions!" ([1st screenshot](#image1))
This message shows when I try to communicate between a Consumer and a Producer.

After talking with a colleague, that is trying to connect the DataSpace Connector with a custom instance of the DAPS, We detected that this message comes from [here](https://github.com/International-Data-Spaces-Association/IDS-Connector-Framework/blob/2d0bbf20f1cb5f89104de0516d97cad95db8b162/base/src/main/java/de/fraunhofer/isst/ids/framework/daps/TokenManagerService.java), in this section of the code: ([2nd screenshot](#image2))

Also, this means that the Connector doesn't make requests to DAPS because the method "aquireToken" breaks before making any HTTP request.

Is this a problem with the self-signed certificate that comes with the Connector?
Or are We setting something wrong in the Connector?

**To Reproduce**
1. Request the description using "POST /api/ids/description"
2. Look in the logs

**Expected behavior**
It is expected that the Connector communicates with DAPS to validate itself.

**Screenshots**
![image1](https://user-images.githubusercontent.com/56237222/122961028-eb79d380-d37b-11eb-89d5-833dd93be6ed.png)
![image2](https://user-images.githubusercontent.com/56237222/122960922-cc7b4180-d37b-11eb-8228-da8f69970be8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 + WSL (Ubuntu)
 - Browser: Chrome
 - Version: Dataspace Connector v5.1.2

**Comment by juliapampus** [comment]
Hey! I guess you just downloaded and executed the code without changing the certificate and deploy mode in the `config.json`? Then, the connector is not able to connect to the DAPS and the Framework will log those "errors" when it tries to retrieve a DAT. Details on how to change the deployment to have a valid IDS communication with a DAPS connection can be found [here](https://international-data-spaces-association.github.io/DataspaceConnector/Deployment/Configuration#step-2-ids-certificate). Nevertheless, two DSCs in test deployment should be able to exchange metadata and data.

**Comment by narcaldas** [comment]
Hi!

Thank you for your response.

Yes, I'm using the default `config.json` of the connector.
Also, as you said, I don't have any problem exchanging data between connectors.

I will take a look at that link.
