### ISSUE TITLE
Unable to build DSC 4.2 in summer 2021

### ISSUE THREAD

**Issue by ChNissenIML** [FraunhoferISST/DataspaceConnector#379]
Dear all,

we have a small docker-compose setup based on DSC 4.2 (commit 5db03461 to be exact) to use for training purposes. While already build images continue to function, we cannot build it anymore. Instead we get a failure regarding lombok:

> #12 7.277 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project dataspace-connector: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x46a6b8d6) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x46a6b8d6 -> [Help 1]

**To Reproduce**
1. checkout DSC commit 5db03461 
2. enter the folder containing the Dockerfile for the DSC
3. run "docker build ."
4. see error

------
 > [maven 6/6] RUN mvn clean package -DskipTests -Dmaven.javadoc.skip=true:
#12 1.577 [INFO] Scanning for projects...
#12 1.843 [INFO]
#12 1.843 [INFO] ---------------< de.fraunhofer.isst:dataspace-connector >---------------
#12 1.851 [INFO] Building dataspace-connector 4.2.0
#12 1.854 [INFO] --------------------------------[ jar ]---------------------------------
#12 3.033 [INFO]
#12 3.034 [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ dataspace-connector ---
#12 3.131 [INFO] Deleting /tmp/target
#12 3.139 [INFO]
#12 3.140 [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven) @ dataspace-connector ---
#12 3.281 [INFO]
#12 3.281 [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ dataspace-connector ---
#12 3.363 [INFO] Using 'UTF-8' encoding to copy filtered resources.
#12 3.369 [INFO] Copying 3 resources
#12 3.392 [INFO] Copying 2 resources
#12 3.403 [INFO]
#12 3.403 [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ dataspace-connector ---
#12 3.588 [INFO] Changes detected - recompiling the module!
#12 3.594 [INFO] Compiling 72 source files to /tmp/target/classes
#12 5.459 [INFO] ------------------------------------------------------------------------
#12 5.461 [INFO] BUILD FAILURE
#12 5.463 [INFO] ------------------------------------------------------------------------
#12 5.466 [INFO] Total time:  3.909 s
#12 5.467 [INFO] Finished at: 2021-06-28T08:58:20Z
#12 5.467 [INFO] ------------------------------------------------------------------------
#12 5.469 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project dataspace-connector: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x48c8c722) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x48c8c722 -> [Help 1]
#12 5.472 [ERROR]
#12 5.472 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#12 5.473 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#12 5.473 [ERROR]
#12 5.473 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#12 5.474 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
------
> executor failed running [/bin/sh -c mvn clean package -DskipTests -Dmaven.javadoc.skip=true]: exit code: 1

**Expected behavior**
The DSC should be build successfully.

**Additionall information**
The POM.xml is missing a property for the lombok Version. I've tried setting the version which was used on the last successful build (early april 2021) but that had no effect.

>  pom.xml | 2 +-
>  1 file changed, 1 insertion(+), 1 deletion(-)
> 
> diff --git a/pom.xml b/pom.xml
> index 57bde5cf..6791f4fc 100644
> --- a/pom.xml
> +++ b/pom.xml
> @@ -299,7 +299,7 @@
>  		<dependency>
>  			<groupId>org.projectlombok</groupId>
>  			<artifactId>lombok</artifactId>
> -			<version>${lombok.version}</version>
> +			<version>1.18.12</version>
>  		</dependency>
>  
>  		
> 

Any idea on how to fix this, without updating the training setup to DSC 5.*?

**Comment by brianjahnke** [comment]
Hi,
i think the problem is in the Dockerfile. Could you please change `FROM maven:latest AS maven` to `FROM maven:3-jdk-11 AS maven` and try again?

**Comment by ChNissenIML** [comment]
Hi,
the suggested change worked. I can build the container locally again.
Thanks a lot.
