### ISSUE TITLE
DSCs v5.2.0 don't communicate on provider-consumer setup via docker 

### ISSUE THREAD

**Issue by martinHska** [FraunhoferISST/DataspaceConnector#403]
**Describe the bug**
I created a provider consumer setup with the dsc v5.2.0 and the [slim deployment example](https://github.com/International-Data-Spaces-Association/IDS-Deployment-Examples/tree/main/dataspace-connector/slim/docker). My setup can be found here here: [provider-consumer.zip](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/6783482/provider-consumer.zip)

Provider runs on localhost:8080
Consumer runs on localhost:8090

On the Swagger UI, I get the following `error 500` when trying to execute `POST /api/ids/description` using the recipient URL of the provider "https://localhost:8080/api/ids/data" when being on the consumer "https://localhost:8090/api/docs" and the other way round:

Response body
> Ids message handling failed. Message could not be sent.

Response header
> cache-control: no-cache,no-store,max-age=0,must-revalidate 
> connection: close 
> content-length: 55 
> content-type: text/plain;charset=UTF-8 
> date: Wed,07 Jul 2021 14:39:00 GMT 
> expires: 0 
> pragma: no-cache 
> strict-transport-security: max-age=31536000 ; includeSubDomains 
> x-content-type-options: nosniff 
> x-frame-options: DENY 
> x-xss-protection: 1; mode=block 

**To Reproduce**
1. Start docker containers with "docker-compose pull and "docker-compose up" using the provided docker-compose.yml
2. Navigate to https://localhost:8090/api/docs
3. Execute `POST /api/ids/description` with recipient URL "https://localhost:8080/api/ids/data"
4. See error 500

**Expected behavior**
Receiving the provider connectors self-description.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox / Edge
 - Version (DSC): 5.2.0
 -  Docker Version 3.5.1

**Additional context**
I tried unsuccessfully to deactivate TLS as mentioned here: [#178](https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/178)

Building the connectors with maven works just fine in this regard.

**Comment by brianjahnke** [comment]
Hi,
please take a look at this [example](https://github.com/International-Data-Spaces-Association/IDS-Deployment-Examples/tree/main/dataspace-connector/provider-consumer). When using docker and communicating between containers you will have to use different urls for the recipients.

**Comment by martinHska** [comment]
Hi Brian, 

thank you for your reply. That helped a lot and now the connectors are able to communicate. What is the reason SSL has to be deactivated? Will I be able to use docker in a productive environment then?

**Comment by brianjahnke** [comment]
Hi martinHska,

i believe the reason for disabling SSL is for the sake of simplicity (@sebplorenz?). The default SSL certificates are only for localhost.
Yes, you should be able to use docker in your productive environment.
