### ISSUE TITLE
Consumed data is binary instead of json

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#406]
I have created a simple provider-consumer example. See https://github.com/sebplorenz/IDS-Deployment-Examples/tree/feature/provider_consumer_example/dataspace-connector/provider-consumer

The source data in this example is a json file provided by the DWD. 
Set up everything as explained in the example. 
When downloading the data with the consumer DSC the data is in binary format and cannot be read by the client.

**Comment by juliapampus** [comment]
Linked to issue #349

**Comment by sebplorenz** [comment]
Any progress on this or #349. I'm still (DSC v6) not able to access the resource of my DWD connector. Is there a workaround to consume json data?

**Comment by sebplorenz** [comment]
I just found out that I can remove the accept-encoding header in the request to fix this. Or set an empty accept-encoding header in a camel route:
```
<removeHeader headerName="Accept-Encoding"/>
```
