### ISSUE TITLE
Meaningful operationIds in OpenApi spec

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#423]
Hi, the OpenApi spec of the DSC contains auto-generated operation ids like this:

https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/5d2425c5d3f6c487a52563f79d974ba3e7abf7c9/openapi.yaml#L694-L699

or this:

https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/5d2425c5d3f6c487a52563f79d974ba3e7abf7c9/openapi.yaml#L804-L809

Since the clients that are generated out of this specification are meant for human use it would be nice if the operationIds would have a meaningful name. For the two examples above this could be getRepresentationRequests and getRepresentationOffers.

**Comment by juliapampus** [comment]
Duplicate of International-Data-Spaces-Association/DataspaceConnector#15

**Comment by juliapampus** [comment]
Duplicate of International-Data-Spaces-Association/DataspaceConnector#15
