### ISSUE TITLE
Test fails when in productive deployment

### ISSUE THREAD

**Issue by HeinrichPet** [FraunhoferISST/DataspaceConnector#429]
**Describe the bug**
On branch 386 the build fails when the DSC is configured for Productive Deployment

**To Reproduce**
Change in config.json from TEST_DEPLOYMENT to
```
  "ids:connectorDeployMode" : {
    "@id" : "idsc:PRODUCTIVE_DEPLOYMENT"
  },
```
and build 
`mvnw clean package`

**Expected behavior**
clean build

**Screenshots & Logs**
Logs:
```
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ContractAgreementHandlerTest.handleMessage_validAgreement_returnMessageProcessedNotificationMessageAndLogToCH:234 ClassCast
[ERROR]   ContractRequestHandlerTest.checkContractRequest_validRequest_returnOk:462 ClassCast
[ERROR]   DescriptionRequestHandlerTest.handleMessage_validResourceDescriptionMsgKnownId_returnResourceDescription:169 ClassCast
[ERROR]   DescriptionRequestHandlerTest.handleMessage_validSelfDescriptionMsg_returnSelfDescription:107 ClassCast
[INFO]
[ERROR] Tests run: 1166, Failures: 0, Errors: 4, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:44 min
[INFO] Finished at: 2021-07-15T22:33:25+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project dataspaceconnector: There are test failures.
[ERROR]
[ERROR] Please refer to C:\IDS\DataspaceConnector\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Files:
[io.dataspaceconnector.service.message.handler.ContractAgreementHandlerTest.txt](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/6826121/io.dataspaceconnector.service.message.handler.ContractAgreementHandlerTest.txt)

[io.dataspaceconnector.service.message.handler.ContractRequestHandlerTest.txt](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/6826118/io.dataspaceconnector.service.message.handler.ContractRequestHandlerTest.txt)

[io.dataspaceconnector.service.message.handler.DescriptionRequestHandlerTest.txt](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/6826117/io.dataspaceconnector.service.message.handler.DescriptionRequestHandlerTest.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version (DSC) v6 - branch 386-ids-configmanager-integration

**Comment by ghost** [comment]
just for info and for the branch hierarchy: needs to be fixed on branch 255

**Comment by brianjahnke** [comment]
Tried it on 255 works without problem.

**Comment by HeinrichPet** [comment]
Works also for me now. Probably it was due to an outdated Java or Intellij version...
