### ISSUE TITLE
Configurable configuration

### ISSUE THREAD

**Issue by mkollenstart** [FraunhoferISST/DataspaceConnector#43]
The configuration, as far as I can see, is now static within the JAR file of the project. Which entails that each time the configuration changes, the JAR has to be built up again.

Is it an idea to have an option to mount configuration on the file system of a Docker container? This enables the connector to use the same Docker image for different configurations, which enhances the ability to practically use the DataspaceConnector.

**Comment by juliapampus** [comment]
This is a very good idea! In the future, the configuration of the connector at runtime will be possible using the Configuration Manager.
