### ISSUE TITLE
GET ​/api​/endpoints does not return datasource

### ISSUE THREAD

**Issue by BastianWel** [FraunhoferISST/DataspaceConnector#438]
Created new generic endpoint and data source.
Addes data source to generic endpoint: PUT /api​/endpoints​/{id}​/datasource​/{dataSourceId}
But GET ​/api​/endpoints does not contain a data source for that generic endpoint.

**Comment by ghost** [comment]
will be fixed within the next seconds

**Comment by ghost** [comment]
fixed (255 & 386): https://github.com/International-Data-Spaces-Association/DataspaceConnector/pull/262/commits/070ccd5573aa5fad43ca08f7d03fbefb9e7aaabe
