### ISSUE TITLE
Add payment details

### ISSUE THREAD

**Issue by HeinrichPet** [FraunhoferISST/DataspaceConnector#439]
**Is your feature request related to a problem? Please describe.**
Various pricing modalities such as "free", "fixed price", "negotiation basis" can be used as a pre-selection to annotate the terms of the contract. Depending on the requirements, additional free text information can be attached.

**Implementation**
See Implementation in metadata broker.
I think it will be done via this contract: https://github.com/International-Data-Spaces-Association/InformationModel/tree/develop/examples/contracts-and-usage-policy/templates/SalesTemplates

**Additional context**
For the time being only the price should be attached, no enforcement or verification if the price was or is payed by the consumer.

**Comment by juliapampus** [comment]
Extend resource by attribute

**Comment by juliapampus** [comment]
as additional field, mapping to `ids:...`
