### ISSUE TITLE
Endpoint for online status

### ISSUE THREAD

**Issue by juliapampus** [FraunhoferISST/DataspaceConnector#44]
For the Configuration Manager and probably other services, it would be interesting to regularly check whether the connector is still "online"/accessible.

**Comment by juliapampus** [comment]
Should there be a separate endpoint for this? @brianjahnke

**Comment by brianjahnke** [comment]
There should be. But I believe the dataspace connector does already support this feature. It just needs to be enabled.

**Comment by brianjahnke** [comment]
The dataspace connector supports springs actuators. The endpoint health can be enabled.
