### ISSUE TITLE
Adding references between resources

### ISSUE THREAD

**Issue by HeinrichPet** [FraunhoferISST/DataspaceConnector#441]
**Describe the solution you'd like**
The meta-data model is extended by additional internal references between resources to indicate internal relationships, e.g.  to mark sample records or to refer to additional records.

**Implementation**
See information model extensions for the metadata broker.

**Comment by juliapampus** [comment]
Resource with additional attribute: list of URIs pointing at other resources. Mapped to `ids:sample`. The sample resource should be a subset of the resource, with an unrestricted usage permission policy attached.

**Comment by juliapampus** [comment]
Sample as additional field: e.g. "ids:sample":"https://sample1, https://sample2" --> mapping to `ids:sample`
