### ISSUE TITLE
Trust-Level

### ISSUE THREAD

**Issue by HeinrichPet** [FraunhoferISST/DataspaceConnector#442]
**Describe the solution you'd like**
Data providers can directly annotate resources that are required to process this data outside of the contract templates, which are required to create trust levels of connectors. The corresponding trust levels are maintained in the user interface. 

**Implementation**
See updated information model for metadata broker

_Note Heinrich: I don't understand that point, because normally the trust-level is and should be defined in the contract.... but for the sake of completeness I'll include it.... we'll see what is expected from the broker_

**Comment by juliapampus** [comment]
Already implemented by security profile restricted policy pattern. Todo: test how this information is displayed at the broker GUI.

**Comment by juliapampus** [comment]
Implemented and tested with DSC and Messaging Services by registering the connector and an example resource successfully (by status code) at the Broker. However, not guaranteed that all new attributes (samples, payment modality, and security level restricted policy) are displayed correctly. The Broker at https://broker.test.mobilitydataspace.io/ shows `Unknown Resource` for all resources on the second page of resources, and an empty connector on the second page of the connectors. Seems to be a GUI error. For reference, compare the 4th and 5th resource of BMW: https://broker.test.mobilitydataspace.io/resources. Also, the GUI crashes when selecting `Dashboard`.

**Comment by juliapampus** [comment]
Screenshots after successful registration:
Connector: 
![image](https://user-images.githubusercontent.com/72392527/129456747-180ac4e0-75fc-4dac-8fae-532af6e2ff85.png)
Details:
![image](https://user-images.githubusercontent.com/72392527/129456754-b0e8e53b-9ce8-4617-89fe-4ba252e95743.png)

Resource:
![image](https://user-images.githubusercontent.com/72392527/129456798-d0db7f74-77f7-444c-8ef2-b5d7d29dc243.png)
Details:
![image](https://user-images.githubusercontent.com/72392527/129456806-584eb556-8a07-485a-96ec-93cdbe7ffbd2.png)

**Comment by sebbader** [comment]
Hi Julia, we are nearly done with resolving this "second page" problem, works already on our testing server. @NehaThawani44 please add a comment here if that one is deployed. Apart of that, it should be fine.
