### ISSUE TITLE
Offer data requests at the metadata broker

### ISSUE THREAD

**Issue by HeinrichPet** [FraunhoferISST/DataspaceConnector#443]
**Is your feature request related to a problem? Please describe.**
Currently only data offers can be registered at the broker.

**Describe the solution you'd like**
Connectors can publish data requests, with the same meta data that is already specified for offers, including licenses, free text description, categories, formats, etc.

**Implementation**
See updated information model / metadata broker

**Comment by juliapampus** [comment]
Lowest priority: extend resource entity by third sub-type. No logic, just mapping to `ids:resourceCatalog` --> `requestedResources`.
