### ISSUE TITLE
/api/examples/policy

### ISSUE THREAD

**Issue by ctoscano-eu** [FraunhoferISST/DataspaceConnector#461]
V6.0.0, POST access to /api/examples/policy

Using this POST method with a body like
{
  "title": "Allow Data Usage",
  "description": "connector-restriction",
  "type": "CONNECTOR_RESTRICTED_USAGE"
}
gives 400 error.

The same happens for all the other examples. The examples PROVIDE_ACCESS and PROHIBIT_ACCESS are the only ones that return the policy.

On the 5.2.1 version, this API was working for all examples.

**Comment by ghost** [comment]
Technically in the example the value for the right operand of the constraint of the connector restricted usage is missing (_url_).

Following works:
```
{
"title": "Allow Data Usage",
"description": "connector-restriction",
"type": "CONNECTOR_RESTRICTED_USAGE",
"url":"http://test"
}
```

More examples:
```
{
"type": "PROVIDE_ACCESS"
}
```

```
{
"type": "PROHIBIT_ACCESS"
}
```

```
{
"type": "N_TIMES_USAGE",
"value":"5"
}
```

```
{
"type": "DURATION_USAGE",
"duration":"PT1M30.5S"
}
```

```
{
"type": "USAGE_DURING_INTERVAL",
"start":"2020-07-11T00:00:00Z",
"end":"2022-07-11T00:00:00Z"
}
```

```
{
"type": "USAGE_UNTIL_DELETION",
"start":"2020-07-11T00:00:00Z",
"end":"2022-07-11T00:00:00Z",
"date":"2020-07-11T00:00:00Z"
}
```

```
{
"type": "USAGE_LOGGING"
}
```

```
{
"type": "USAGE_NOTIFICATION",
"url": "https://localhost:8080/api/ids/data"
}
```

```
{
"type": "SECURITY_PROFILE_RESTRICTED_USAGE",
"profile": "BASE_SECURITY_PROFILE"
}
```

**Comment by ctoscano-eu** [comment]
Thank you, the information provided resolved the issue. Perhaps putting these examples in the user manual would help others migrate from the previous version (5.2.1) ....
