### ISSUE TITLE
API endpoint to get possible values for de.fraunhofer.iais.eis.SecurityProfile

### ISSUE THREAD

**Issue by BastianWel** [FraunhoferISST/DataspaceConnector#464]
For the "Restrict to specific Security Level" contract the user has to choose the profile in the UI.
For now I hardcoded the profiles (idsc:TRUST_SECURITY_PROFILE, idsc:BASE_SECURITY_PROFILE, idsc:TRUST_PLUS_SECURITY_PROFILE).
Would it be possible to get the possible types i.e. via Enum API Endpoint (GET /api/configmanager/enum/)?

**Comment by ghost** [comment]
Is on PR, will be /api/configmanager/enum/securityprofile
