### ISSUE TITLE
Support for resource URIs in policy constraints' rightOperand

### ISSUE THREAD

**Issue by trueg** [FraunhoferISST/DataspaceConnector#474]
Currently when defining a policy rule which restricts usage based on a connector one requires the use or a typed xsd:anyURI literal:
```
{
    "@type" : "ids:Constraint",
    "ids:rightOperand" : {
      "@value" : "https://example.com",
      "@type" : "http://www.w3.org/2001/XMLSchema#anyURI"
    },
    "ids:leftOperand" : {
      "@id" : "idsc:SYSTEM"
    },
    "ids:operator" : {
      "@id" : "idsc:SAME_AS"
    }
  }
```

This is confusing (for anyone used to working with RDF at least) and does not match the IDS ontology which defines rdfs:Resource as the range for ids:rightOperand: https://international-data-spaces-association.github.io/InformationModel/docs/index.html#rightOperand

As a solution I propose to include support for resource URIs which allows the following:
```
{
    "@type" : "ids:Constraint",
    "ids:rightOperand" : {
      "@id" : "https://example.com"
    },
    "ids:leftOperand" : {
      "@id" : "idsc:SYSTEM"
    },
    "ids:operator" : {
      "@id" : "idsc:SAME_AS"
    }
  }
```

**Comment by trueg** [comment]
@juliapampus Why was this issue marked as "out of scope" and what exactly does that mean?

**Comment by juliapampus** [comment]
`As a solution I propose to include support for resource URIs which allows the following.`
Counter question: Why exactly do you need extra support for this? I just again tried this policy myself a few minutes ago with the contract_negotation_connector_restricted_access.py script. This works either with the @type and @value or with the @id. Did you have any problems with this? 

As we are using the Infomodel library, the DSC is bound to the return value of the serializer and we just added the received JSON-LD as an example to docs and scripts - as we cannot afford to manually adapt all possible values all the time. If RDF allows it, the Infomodel serializer will as well, so go for it. :)

The Infomodel lib returning this kind of representation we cannot change, so this adjustment would be out-of-scope for us.

**Comment by trueg** [comment]
It did not work when I tried it but that was a while ago. If it works now then we can disregard this issue and consider it as being fixed. :)
