### ISSUE TITLE
Error starting CamelContext (camel-1) due to exception thrown: Failed to start route idscpServer because of null

### ISSUE THREAD

**Issue by ctoscano-eu** [FraunhoferISST/DataspaceConnector#475]
I have just installed a real certificate I got from Gerd and made all the necessary configuration on the dataspace connector.
The 6.0.0 connector launches and at the very end presents the error:
    Error starting CamelContext (camel-1) due to exception thrown: Failed to start route idscpServer because of null
    ..... (see the attachment)

Any help would be very much appreciated.

[error.log](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/6901226/error.log)

**Comment by ronjaquensel** [comment]
Hi, 

the error seems to be related to IDSCP2 not being able to read the certificate correctly.
do you want the connector to communicate via IDSCP2? If not, the property `idscp2.enabled` should be set to false. Then, the IDSCP2 server does not try to start. If you do want to use IDSCP2 for communication, the path to the IDS certificate also has to be set in the property `idscp2.keystore`, as IDSCP2 requires a valid IDS certificate to start.

**Comment by ctoscano-eu** [comment]
thank you, I disabled the IDSCP2, I don't need  to use the IDSCP2.
