### ISSUE TITLE
Create new artifact with Generic Endpoint ID / Data Source ID

### ISSUE THREAD

**Issue by BastianWel** [FraunhoferISST/DataspaceConnector#476]
In the UI, the user can store the URL and authentication data for database/REST by creating Backend Connections (generic endpoints) so that they do not have to re-enter it for each resource.
When creating a resource, the user only selects the Backend Connection to use.
The authentication data is also required to create an artifact. Since the UI does not get this authentication data of the Generic Endpoint returned, the UI would need to have the option to specify the Generic Endpoint ID or Data Source ID in the artifact API instead of the authentication data directly.
The DSC could then set the associated authentication data for the artifact.

**Comment by HeinrichPet** [comment]
Related: #514
