### ISSUE TITLE
How to set API Key for Generic Endpoints? 

### ISSUE THREAD

**Issue by BastianWel** [FraunhoferISST/DataspaceConnector#514]
Authentication data is added to backend Generic Endpoints via Data Sources:
PUT ​/api​/endpoints​/{id}​/datasource​/{dataSourceId}
The Swagger documentation of POST ​/api​/datasources is
```
{
  "authentication": {
    "key": "string",
    "value": "string"
  },
  "type": "Database"
}
```
I am not sure how to set API Key for this endpoint and did not find any other documentation on this topic by now.

Needed for [UI Issue 70](https://github.com/International-Data-Spaces-Association/DataspaceConnectorUI/issues/70)

**Comment by juliapampus** [comment]
This API Key Issue refers to API Key authentication for artifacts. You cannot set this for a data source by now, but for the artifact entity.

**Comment by BastianWel** [comment]
OK, thank you.
Maybe we should extend this in the DataSource so that the user can save the API key authentication directly with the Backend Connection (Generic Endpoint) just like BasicAuth.
