### ISSUE TITLE
Consumer cannot log to Clearing House

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#536]
I've checked the Clearing House logging with the provider-consumer-example. Currently, the consumer cannot log or query the Clearing House with the agreement Id.

Mark Gall pointed out, that, for the consumer to have access to the CH logs with the PID (= agreement ID), the Provider must first explicitly create the PID with a RequestMessage to this endpoint  https://ch-ids.aisec.fraunhofer.de/process/<PID> with the following content:
```
`{
  "owners": ["<provider-connector-identifier>", "<consumer-connector-identifier"]
}`
```

**Comment by ghost** [comment]
Note: Seems to be a new CH functionality. This step to create a PID without further context to make them usable for multiple connectors (shared-PID) does not seem to be part of the (pre-)specification of a ClearingHouse (yet), would be good if it would be added there as well.

At the moment, 3 endpoints for the CH are mentioned there:
- POST /messages/log/{pid} (Creates a new log entry under the given process id)
- POST /messages/query/{pid} (Finds all log entries stored under the given process id pid)
- POST /messages/query/{pid}/{id} (Finds the log entry with the given id stored under the given process id pid)

This new functionality to give access permission for a PID to multiple connectors from the creator of the PID, would need to be added with endpoint-documentation and the existing spec adjusted (_"Processes can be created by any IDS connector with a valid DAT, who becomes the owner of the process. Only the owner of the process may read or write data in the process."_).

https://github.com/International-Data-Spaces-Association/IDS-G-pre/tree/clearinghouse/Components/ClearingHouse

_If there is a newer specification, please let me know, is also interesting for IDS-Messaging-Services ClearingHouse-Module, though the IDS-Messaging-Services not relevant to this issue._

**Comment by ghost** [comment]
Note: After short testing the new endpoint should be `POST /process/{pid}` with the PID to create as path-param, can return rejection-message if PID already exists. I do not know how the scope of the PID is, whether globally a PID may not be registered twice no matter from which connector it was created, or if PIDs are registered within the CH to the owner-connectors.

**Comment by sebplorenz** [comment]
Hi, wich version will support this feature and when will it be released?

**Comment by brianjahnke** [comment]
Hi,

the upcoming release v6.3.0. The feature already existing on the head.
