### ISSUE TITLE
Artifact is not downloaded from provider when doing POST /api/artifacts/{id}

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#543]
I have realized the following, IMHO inconsistent, behavior when downloading an artifact.
On the consumer side, I created an agreement with download=false.
When doing a GET request on /api/artifacts/{id} without any additional path parameters, the artifact is downloaded from the provider connector and returned within the response, as expected.
When doing a POST request on /api/artifacts/{id} with an empty body, the locally cached artifact is returned within the response.
Expected behavior: When doing the POST request, the artifact should be downloaded as well.

EDIT: The behavior described above leads to the following bug: If the agreement is created and the first request to get the resource is the POST request described above, then the DSC replies with a 500 - Internal Server Error.

**Comment by brianjahnke** [comment]
Hi,
when you call the data endpoint, the DSC checks if the local artifact's data has the same bytesize as the provider's artifact. If they are the same the cached version is returned since you already have the artifact downloaded.
If you need a download you can perform a force download via the request body.

**Comment by sebplorenz** [comment]
Hi @brianjahnke 

The resource on the consumer side has not been updated for days, even if the artifact on the provider side did. When setting the logs to debug I did not see any request from the consumer DSC to the provider DSC. 

The POST request should never end in an Internal Server Error response.

On the provider side the artifact is coming from a backend API. This API has not been called when the consumer backend was requesting the resource via POST.

**Comment by juliapampus** [comment]
- [ ] Check error 500
- [ ] Add params from GET to POST
