### ISSUE TITLE
Bytesize not updated

### ISSUE THREAD

**Issue by brianjahnke** [FraunhoferISST/DataspaceConnector#547]
**Describe the bug**
When resetting the artifacts data the artifact bytesize is not cleared.

**To Reproduce**
Look at ArtifactFactory::updateByteSize.
When the new bytes are null no changes are applied.

**Expected behavior**
When setting no data, the bytesize and checksum should be 0.

**Desktop (please complete the following information):**
 - Version (DSC) any

**Comment by ghost** [comment]
Consuming resources (e.g. via DSC UI) saves `byteSize` and `checkSum` in `"additional"` and not in artifact fields itself.
`updateByteSize` isn't working on the "additional" fields for consumed resources.

![image](https://user-images.githubusercontent.com/75306992/133986322-51c53f83-f0a3-48b6-87fd-cb0f06d8cd10.png)
