### ISSUE TITLE
Subscription notification does not work

### ISSUE THREAD

**Issue by trueg** [FraunhoferISST/DataspaceConnector#552]
## Problem Description
When setting up a subscription for an artifact as described in [Subscription](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/Subscription), changing the artifact's data does not trigger the notification as expected.

## How To Reproduce
I created a small script based on the existing ones which I [commited to my fork](https://github.com/trueg/DataspaceConnector/commit/f9c6ac814eec601b9c526acf7ebadf269dc3d895). It uses a provider and a consumer connector and does the following:
- Create a catalog, offer, representation and artifact in the provider
- Create a contract in the consumer
- Test fetching the data from the consumer
- Subscribe to the provider via /api/ids/subscribe
- Subscribe to the consumer via /api/subscriptions (a simple web request logger can be used to see if the notification requests arrive)

Now the data in the provider's artifact can be changed via a PUT to /api/artifacts/xxxxx/data. After this the consumer can see the new data but there is no notification request.

## System:
 - The test has been executed in a small Kubernetes (microks) cluster with two connector instances and a web request logger.

**Comment by ronjaquensel** [comment]
This issue has been discussed with the author and was related to the setup. The subscription mechanism works as expected.
