### ISSUE TITLE
[AppStore documentation] Suggested addition: Valid connector certificate required

### ISSUE THREAD

**Issue by ghost** [FraunhoferISST/DataspaceConnector#553]
The current IDS AppStore sends a RejectionMessage on incoming messages without a valid DAT. Accordingly, as with the Metadata Broker running in the IDS-Lab, a valid connector certificate must be available for communication with the AppStore.

Could either be added here under _Note_:
https://international-data-spaces-association.github.io/DataspaceConnector/Deployment/Configuration#step-2-ids-certificate

or as Note in the AppStore communication guide:
https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/IdsEcosystem/AppStore

Should definitely be kept in mind, as examples, like the full-deployment-example, won't work out-of-the-box with the AppStore.

**Comment by juliapampus** [comment]
- [ ] I just recognized that the images are broken. I will fix this. 
- [x] In addition, the DAPS documentation (as requested by Hendrik) will be extended.
