### ISSUE TITLE
Documentation: Referenced Licenses

### ISSUE THREAD

**Issue by SebastianOpriel** [FraunhoferISST/DataspaceConnector#561]
At https://international-data-spaces-association.github.io/DataspaceConnector/Features a section named IDS Communication can be found. The licences of IDS Broker and ParIS are described as "open core", but they are Apache 2.0. The components themselves are just the open core of IDS Broker/ParIS.

**Comment by brianjahnke** [comment]
Hi,
you are correct. Thanks for spotting it!
