### ISSUE TITLE
Documentation doesn't state an important aspect of providing "accessUrl"

### ISSUE THREAD

**Issue by muzzletov** [FraunhoferISST/DataspaceConnector#564]
Since you have to supply a remote access url with a trailing path the documentation's example is somewhat misleading
since the given example is just a base path.

Not providing a URL with a path creates a local data object - accessing the artifact's data url then causes a NPE.

**Comment by brianjahnke** [comment]
Hi,
just to verify that I understand the problem described:
1. An artifact is created with the the accessUrl set to a value that is not an URL.
2. On access of the artifact's data the connector throws an NPE/returns HttpCode 500.

**Comment by muzzletov** [comment]
Hello!

No, that's not the issue. It is a valid url, it just doesn't conform to having a path.

For example:

https://URL-WITHOUT-A-PATH.IT - this one would cause a NPE
https://URL-WITH-A-PATH.IT/THIS-IS-THE-PATH

The issue is at the ArtifcatFactory, if I remember correctly, where you check if the path length of a valid URI is not empty.
