### ISSUE TITLE
HTTP-GET on Policy Examples throws Exception

### ISSUE THREAD

**Issue by SebastianOpriel** [FraunhoferISST/DataspaceConnector#565]
At https://international-data-spaces-association.github.io/DataspaceConnector/Documentation/v6/UsageControl it is said, that POST /api/examples/policy can be used for policy examples.

If using GET-Method (without parameter), an exeption is thrown on both endpoints: policy and validation 
```
WARN - Failure in @ExceptionHandler io.dataspaceconnector.controller.exceptionhandler.GlobalExceptionHandler#handleAnyException(RuntimeException)
java.lang.IllegalStateException: Could not resolve parameter [0] in public org.springframework.http.ResponseEntity<net.minidev.json.JSONObject> io.dataspaceconnector.controller.exceptionhandler.GlobalExceptionHandler.handleAnyException(java.lang.RuntimeException): No suitable resolver
```

Expected behaviour: `This application has no explicit mapping for /error, so you are seeing this as a fallback.`

**Comment by brianjahnke** [comment]
Hi,
i think there are two problems in the behaviour of the DSC.
1. The global exceptionhandler should not throw an exception.
2. The connector should respond with Method Not Allowed, when performing a GET on the endpoint.
