### ISSUE TITLE
Documentation: Broken links in IdentityProvider page

### ISSUE THREAD

**Issue by SebastianOpriel** [FraunhoferISST/DataspaceConnector#570]
https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/IdsEcosystem/IdentityProvider

Links to documentation of DAPS and DAT are broken.

**Comment by SebastianOpriel** [comment]
Link to documentation of Broker is affected too (https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/IdsEcosystem/Broker)

**Comment by SebastianOpriel** [comment]
Documentation of ClearingHouse too: https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/IdsEcosystem/ClearingHouse

**Comment by juliapampus** [comment]
Thanks for the hint. Will be updated soon.
