### ISSUE TITLE
Huge error messages for ResourceNorFoundExceptions

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#571]
If a consumer requests a resource with an ID that does not exist on the provider side, then the provider:
1. Logs an unnecessary error message.
2. It logs 500 lines of Stack Trace.

...

**Comment by brianjahnke** [comment]
Hi,
could you please be more specific (e.g. which version are you using)? Why are the lines unnessary?

**Comment by sebplorenz** [comment]
I'm using DSC 6.2.0 on the provider side. A client requested an artifact with an id that did not exist on this DSC 6.2.0 provider DSC (because its database was deleted). It is normal, that a resource with a requested id might not exist on the connector. This is not a connector error and should not be logged as such.
