### ISSUE TITLE
Broker registration fails for bootstrapped resources

### ISSUE THREAD

**Issue by ronjaquensel** [FraunhoferISST/DataspaceConnector#577]
**Describe the bug**
Registering a resource that has been created by bootstrapping fails with the following error:

```
{
  "reason": {
    "properties": null,
    "@id": "https://w3id.org/idsa/code/INTERNAL_RECIPIENT_ERROR"
  },
  "payload": "500 - Server Error",
  "type": "de.fraunhofer.iais.eis.RejectionMessageImpl"
}
```

This is not the case for resources that have been created via the API endpoints.

Some values are also doubled in the bootstrapped entities, e.g. checkSum for artifact.

**To Reproduce**
1. Checkout *main* branch as is.
2. Set bootstrap.enabled to true in application properties.
3. Start the connector.
4. See log message: *An error occurred while registering resources at the broker.*
5. Try to register one of the resources created by bootstrapping at broker manually via */api/ids/resource/update*
6. See above mentioned error as response.

**Expected behavior**
Registration of bootstrapped resources should complete without error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version (DSC): 6.2.0

**Comment by HeinrichPet** [comment]
Workaround until a fix is available: 

Do not use `ids:language` for resources via bootstrap.
https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/6d27e10475515eb86f9fa8e803d38f6ce967a49d/src/test/resources/bootstrap/catalog2.jsonld#L8-L16
In this example delete line 12-16.
