### ISSUE TITLE
Authorization Requests should be configurable

### ISSUE THREAD

**Issue by edgardmarx** [FraunhoferISST/DataspaceConnector#627]
**Is your feature request related to a problem? Please describe.**
Currently the Authorization Requests are mapped inside the class `io.dataspaceconnector.config.ConfigurationAdapter`.
This approach overrides properties passed as parameters in the i.e. `application.properties` configuration file.

A typical case is when a user wants to handle Access rights through different user authentication system i.e. Keycloak.
In this case, a general solution is to disable the authentication by adding the following parameters to the `application.properties`:

```
security.ignored=/**
spring.security.enabled=false
management.security.enabled=false
security.basic.enabled=false
```

However, this approach will not work, because the URL Authorization Requests mappings are hardcoded:

```
 http
                .sessionManagement()
                    .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                    .and()
                .authorizeRequests()
                .antMatchers("/", "/api/ids/data").anonymous()
                .antMatchers("/api/subscriptions/**").authenticated()
                .antMatchers("/api/**").hasRole("ADMIN")
                .antMatchers("/actuator/**").hasRole("ADMIN")
                .antMatchers("/database/**").hasRole("ADMIN")
                .anyRequest().authenticated()
                .and()
                .csrf().disable()
                .httpBasic()
                .authenticationEntryPoint(authenticationEntryPoint());
        http.headers().xssProtection();
```
**Describe the solution you'd like**
Pass the configuration of Authorization Requests through `applicaton.properties` or configuration files.

**Comment by goekhanKahriman** [comment]
Hi @edgardmarx , are you satisfied with the solution in the pull request.

With the current solution the security can be enabled or disabled via a property.

Please let us know, if you need the properties 
```
security.ignored=/**
spring.security.enabled=false
management.security.enabled=false
security.basic.enabled=false
```
in the application.properties to disable the authentication.

**Comment by edgardmarx** [comment]
It seems good, thank you very much.
