### ISSUE TITLE
Unable to get a resource-specific description

### ISSUE THREAD

**Issue by MikhailGordienk** [FraunhoferISST/DataspaceConnector#634]
**Describe the bug**

According to the documentation, request to `/api/ids/data` must return resource-specific description when elementId is specified.
In fact, the same response containing the overall connector description is returned.

**To Reproduce**
1. Perform all the steps from the Provider section to create a resource, contract etc.
2. Make a request to `/api/ids/data` providing the same host as recipient and offer-id as elementId

**Expected behavior**

Description of the `ids:Resource` type returned.

**Actual behavior**

Description of the `ids:BaseConnector` is returned.

**Desktop (please complete the following information):**
 - Version 6.2.0

**Additional context**
_Full_ configuration from Examples. A single connector instance is used, so it requests a description from itself.

**Comment by goekhanKahriman** [comment]
Hi, can you give us a little more detail on how you tried to request resource specific description. Did you create a description request message? Which API did you use?

**Comment by MikhailGordienk** [comment]
Hello!

I did _Step 2: Query Provider - Request Resource Metadata_ and used the ID of the offer created on the very first step in the _Provider_ section.

**Comment by goekhanKahriman** [comment]
Hi, at the moment we can not reproduce this failure. Can you give us more information about your created resource. Did you use Swagger, the UI or Python scripts to create a full resource ?

Alternatively you can go to the application.properties and set following properties:
```
## Starting path for bootstrapping
bootstrap.path=./src/test/resources
bootstrap.enabled=true
```

This will provide example resources and then you can follow on with these steps:

1. Call API POST - api/ids/description with recipient: https://localhost:8080/api/ids/data
2. Call API POST - api/ids/description with **recipient**: https://localhost:8080/api/ids/data and **elementId**:  https://localhost:8080/api/offers/...

You then should see the resource-specific description.

**Comment by MikhailGordienk** [comment]
I do not want to use generated resources, I want to repeat the steps described in the documentation for Provider and Consumer.
Here is the small postman collection (and environment) I've created to perform only the steps I needed. Please check it out, with the last request I expect to get a Resource-specific description (for the specified offer-id), not the `ids:BaseConnector`.

[postman.zip](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7258950/postman.zip)

**Comment by juliapampus** [comment]
Hi @MikhailGordienk, I had a look at your Postman collection. I executed every step successfully. Within the last step, you set the offer-id (e.g. db70c326-778f-4e6a-9932-ca4008280665) as the elementId. This is wrong. It should be the offer-location (e.g. https://localhost:8080/api/offers/db70c326-778f-4e6a-9932-ca4008280665) as this is the complete url and handled as the id for any ids related communication.

**Comment by MikhailGordienk** [comment]
I tried both, with the location the response is the following:

```
{
    "reason": {
        "properties": null,
        "@id": "https://w3id.org/idsa/code/NOT_FOUND"
    },
    "payload": "The requested element https://localhost:8080/api/offers/bd55d6d4-ef2f-4882-8584-cfea59e4bd8a could not be found.",
    "type": "de.fraunhofer.iais.eis.RejectionMessageImpl"
}
```

which is also not good.
