### ISSUE TITLE
Example policy validation does not work

### ISSUE THREAD

**Issue by MikhailGordienk** [FraunhoferISST/DataspaceConnector#642]
**Describe the bug**

POST `/api/examples/validation` returns 200 (OK) for "dummy" JSON

**To Reproduce**
1. Execute POST `/api/examples/validation` providing the following JSON:

```
{
    "@type": "ids:Permission",
    "@id": "https://anything",
    "ids:target": "anything",
    "ids:description": [
        {
            "@value": "anything",
            "@type": "http://anything"
        }
    ],
    "ids:title": [
        {
            "@value": "anything",
            "@type": "http://anything"
        }
    ],
    "ids:action": [
        {
            "@id": "anything"
        }
    ]
}
```

**Expected behavior**

Validation fails

**Desktop (please complete the following information):**
 - Version 6.2.0

**Additional context**

_Full_ docker-compose from the Examples

**Comment by juliapampus** [comment]
Hi @MikhailGordienk. I cannot reproduce your problem. Tried it with Swagger and Postman:

```
curl --location --request POST 'https://localhost:8080/api/examples/validation' \
--header 'Authorization: Basic YWRtaW46cGFzc3dvcmQ=' \
--header 'Content-Type: text/plain' \
--data-raw '{
    "@type": "ids:Permission",
    "@id": "https://anything",
    "ids:target": "anything",
    "ids:description": [
        {
            "@value": "anything",
            "@type": "http://anything"
        }
    ],
    "ids:title": [
        {
            "@value": "anything",
            "@type": "http://anything"
        }
    ],
    "ids:action": [
        {
            "@id": "anything"
        }
    ]
}'
```

This request responds a 200:
![image](https://user-images.githubusercontent.com/72392527/135856857-62e8cfaa-1957-44a8-8910-2f9711845ffc.png)

**Comment by MikhailGordienk** [comment]
But that is exactly what I am talking about. Validation should fail, because there is no such action as "anything", nor there is such a target.

**Comment by juliapampus** [comment]
This issue comes from the IDS Infomodel Serializer, there is nothing we can do for the moment. Maybe we can address this problem in [this](https://github.com/eclipse-dataspaceconnector/IDS-Serializer) repository for further Infomodel and serializer versions.

**Comment by juliapampus** [comment]
This is an issue that could be improved by both the DSC and the IDS Infomodel Serializer. Maybe we can address this problem in [this](https://github.com/eclipse-dataspaceconnector/IDS-Serializer) repository for further Infomodel and serializer versions, and in the EDC. This is out of scope for this project as this REST endpoint was only meant to provide a possibility to check any value against the IDS Infomodel serializer.
