### ISSUE TITLE
Incorrect Permission deserialization

### ISSUE THREAD

**Issue by MikhailGordienk** [FraunhoferISST/DataspaceConnector#644]
**Describe the bug**

The action array and the target artifact do not get deserialized when using the sample policy.
I believe this affects all contract negotiations.

**To Reproduce**
1. Use  POST `/api/examples/policy` with the following payload to generate sample policy:

```
{
    "type": "PROVIDE_ACCESS",
    "title": "cillum et",
    "description": "in et velit mollit"
}
```

2. Use POST `/api/examples/validation` with the following payload:

```
{
  "@type" : "ids:Permission",
  "@id" : "https://w3id.org/idsa/autogen/permission/43f3b3ae-eaef-46a8-b4af-73b13c4da545",
  "ids:title" : [ {
    "@value" : "Allow Data Usage",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:description" : [ {
    "@value" : "provide-access",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:assigner" : [ ],
  "ids:assignee" : [ ],
  "ids:postDuty" : [ ],
  "ids:constraint" : [ ],
  "ids:action" : [ {
    "@id" : "https://w3id.org/idsa/code/USE"
  } ],
  "ids:target": "https://localhost:8080/api/artifacts/6b08165a-430b-4317-a1cf-0ea7f13041bd",
  "ids:preDuty" : [ ]
}
```

4. Create a breakpoint in _DeserializationService.getRule()_ and check the results. The mentioned fields will be empty.

**Expected behavior**

All fields are properly deserialized.

**Screenshots & Logs**

![policy_deserialization_bug_1](https://user-images.githubusercontent.com/86295931/135437411-27801bb9-d4e8-4f3c-a729-63dd62955ec6.PNG)

**Desktop (please complete the following information):**
 - Version 6.2.0

**Additional context**

_Full_ docker-compose from the Examples

**Comment by goekhanKahriman** [comment]
Hi @MikhailGordienk , thank you for your feedback.
I can reproduce the incorrect deserialization of the  permission.
I have forwarded it to the infomodel serializer developers and they are currently looking into the deserialization failure. I will get back to you as soon as we have more information regarding this.

**Comment by goekhanKahriman** [comment]
The problem with not setting the action and target fields when deserializing is that the JSON in the second step is not correct. 
At the beginning of the JSON the context part is missing and at ids:target the "@id"-Information is missing.
Try to run the whole thing again with the following JSON:
```
{
  "@type" : "ids:Permission",
  "@id" : "https://w3id.org/idsa/autogen/permission/43f3b3ae-eaef-46a8-b4af-73b13c4da545",
  "ids:title" : [ {
    "@value" : "Allow Data Usage",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:description" : [ {
    "@value" : "provide-access",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:assigner" : [ ],
  "ids:assignee" : [ ],
  "ids:postDuty" : [ ],
  "ids:constraint" : [ ],
  "ids:action" : [ {
    "@id" : "https://w3id.org/idsa/code/USE"
  } ],
  "ids:target": "https://localhost:8080/api/artifacts/6b08165a-430b-4317-a1cf-0ea7f13041bd",
  "ids:preDuty" : [ ]
}
```

**Comment by thebe14** [comment]
I do not see how this JSON  is different from the one in 2. from the bug report

**Comment by goekhanKahriman** [comment]
Sorry has been my mistake, have copied and pasted the old JSON.
With the following JSON it should work:
```
{
   "@context":{
      "ids":"https://w3id.org/idsa/core/",
      "idsc":"https://w3id.org/idsa/code/"
   },
   "@type":"ids:Permission",
   "@id":"https://w3id.org/idsa/autogen/permission/e3a879c1-2ab8-41ce-9357-c8f3fc0c61c3",
   "ids:target":{
      "@id":"https://example.org"
   },
   "ids:preDuty":[
      
   ],
   "ids:postDuty":[
      
   ],
   "ids:description":[
      {
         "@value":"provide-access",
         "@type":"http://www.w3.org/2001/XMLSchema#string"
      }
   ],
   "ids:title":[
      {
         "@value":"Allow Data Usage",
         "@type":"http://www.w3.org/2001/XMLSchema#string"
      }
   ],
   "ids:action":[
      {
         "@id":"https://w3id.org/idsa/code/USE"
      }
   ],
   "ids:assigner":[
      
   ],
   "ids:constraint":[
      
   ],
   "ids:assignee":[
      
   ]
}
```

**Comment by MikhailGordienk** [comment]
Please try to use the attached collection on your side. The policy format you proposed doesn't work in this scenario. I think it is the same deserialization problem. The _Send IDS contract request message_ fails.


[postman.zip](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7372769/postman.zip)

**Comment by goekhanKahriman** [comment]
I tried to reproduce the single steps with version 6.2.0.
However, I can not understand how you have generated this following payload:
```
{
  "@type" : "ids:Permission",
  "@id" : "https://w3id.org/idsa/autogen/permission/43f3b3ae-eaef-46a8-b4af-73b13c4da545",
  "ids:title" : [ {
    "@value" : "Allow Data Usage",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:description" : [ {
    "@value" : "provide-access",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:assigner" : [ ],
  "ids:assignee" : [ ],
  "ids:postDuty" : [ ],
  "ids:constraint" : [ ],
  "ids:action" : [ {
    "@id" : "https://w3id.org/idsa/code/USE"
  } ],
  "ids:target": "https://localhost:8080/api/artifacts/6b08165a-430b-4317-a1cf-0ea7f13041bd",
  "ids:preDuty" : [ ]
}
```
When I execute POST on /api/examples/policy with the sample policy, i got following payload:
```
{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:Permission",
  "@id" : "https://w3id.org/idsa/autogen/permission/a7c139b4-16b4-4838-84a4-0d80fb0ca93e",
  "ids:description" : [ {
    "@value" : "provide-access",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:title" : [ {
    "@value" : "Allow Data Usage",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:assignee" : [ ],
  "ids:assigner" : [ ],
  "ids:postDuty" : [ ],
  "ids:action" : [ {
    "@id" : "https://w3id.org/idsa/code/USE"
  } ],
  "ids:constraint" : [ ],
  "ids:preDuty" : [ ]
}
```
Also, the question is how did you get the target information into the payload?

**Comment by MikhailGordienk** [comment]
The `ids:target` field is required according to the [documentation](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/Consumer#step-3-negotiate-a-contract-agreement). The same example goes without `@context` section. The policy format from  `/api/examples/policy` gives an error on the "agreement" step if the `target` is not specified (without @id, as it is in the openapi.yaml).

Could you please share the postman collection that works for the producer/consumer case? You could take mine and just provide the right payloads. This I believe would be the best way. You could also attach the collection to the documentation.

**Comment by juliapampus** [comment]
Just tried with v7 (serializer v4.2.8). The problem seems to still exist. Maybe we can address this in future developments: https://github.com/eclipse-dataspaceconnector/IDS-Serializer.
