### ISSUE TITLE
[actuator] Expiration date of certificates

### ISSUE THREAD

**Issue by ghost** [FraunhoferISST/DataspaceConnector#648]
Feature request received:
Is it possible to include the expiration date for the TLS certificate and the connector certificate into the actuator/info API?

Messaging-Services already provide a getCertExpiration() to get the expiration date of the connector certificate.

**Comment by juliapampus** [comment]
When we add such information, we should provide even more details, e.g. when the DAT was last issued and from what DAPS it was generated.

**Comment by SebastianOpriel** [comment]
This feature is more a maintenance feature, to be informed about upcoming TLS expiration. I as a connector admin want to get notified about this expiration and therefore would connect monitoring tools towards this API.
DAT monitoring is IMHO a whole different thing in this case.

**Comment by juliapampus** [comment]
Nevertheless, to avoid API changes later on, it must be carefully considered how the JSON object can be structured in a meaningful way. The object and attribute naming in PR #649 is not the best. And it includes DAT infos.
