### ISSUE TITLE
Description Request results in HTTP 500 response if resource does not exist on requested connector

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#65]
If a description request (/admin/api/request/description) is sent to the connector with a requested resource URI that does not exist in the requested connector, then the connector returns a HTTP Status Code 500 with the message.

In the example setup with two connectors the following request to the data-consumer connector:

`https://localhost:8080/admin/api/request/description?recipient=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fids%2Fdata&requestedArtifact=https%3A%2F%2Fw3id.org%2Fidsa%2Fautogen%2FpublicKey%2F78eb73a3-3a2a-4626-a0ff-631ab50a00f9`

would give the following response:

`Metadata could not be saved: Could not resolve type id 'ids:RejectionMessage' as a subtype of [simple type, class de.fraunhofer.iais.eis.DescriptionResponseMessage]: known type ids = [ids:DescriptionResponseMessage]
 at [Source: (String)"{"@context":{"ids":"...`

Expected:
Status Code 404 with the rejection message from the requested connector as payload.

**Comment by brianjahnke** [comment]
Hello,

we will try to reproduce the problem. Which version of the connector are you using?

**Comment by brianjahnke** [comment]
We were able to reproduce the problem. It will be added to the todo list.

**Comment by brianjahnke** [comment]
As of commit b4082fb7e2155c9c115ae42cc445391508aa1c18 the behaviour of this endpoint has changed. This issue will be closed. If you still consider the current behaviour a problem, feel free to reopen this or another issue.
