### ISSUE TITLE
Admin credentials are used to access description and contract endpoints

### ISSUE THREAD

**Issue by MikhailGordienk** [FraunhoferISST/DataspaceConnector#661]
**Describe the bug**

Unable to use _App_ credentials to request a resource description or initiate contract negotiation.
Currently, the admin credentials are required to call these endpoints.

**To Reproduce**

1.Call POST `/api/ids/contract` with App credentials or call POST `/api/ids/description`

**Expected behavior**
The endpoint is accessible.

**Desktop (please complete the following information):**
 - Version 6.2.0

**Additional context**
_Full_ docker-compose from the Examples

**Comment by juliapampus** [comment]
The app account is provided for services that want to subscribe to the connector. As they should not have any admin rights, e.g. for negotiating a contract, the app account only has permissions for the subscription endpoints, as described [here](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/Subscription#step-1-create-a-non-ids-subscription).

**Comment by MikhailGordienk** [comment]
Thanks for the clarification, but that means the Admin credentials are the only ones that can be used to call the connector, which is still an issue.

**Comment by juliapampus** [comment]
Could be solved by either implementing identity and role management or setting up a reverse proxy.
