### ISSUE TITLE
Technologies used. Further documentation

### ISSUE THREAD

**Issue by jmartinezsqs** [FraunhoferISST/DataspaceConnector#665]
I am working on validating the DSC for the reference testbed of IDSA and encountered a problem. The technologies being used by the connector are listed in the DSC's documentation but there is no information about the versions implemented. The security aspect of the connector's validation is required to have this information in order to determine what kind of vulnerabilities are added to the project by using specific versions of the technologies.

I would like you to add this information to the documentation of the component, that way we can test its safety in-depth and come up with a more complete validation report.

Let me know if you need anything from me. Thanks

**Comment by brianjahnke** [comment]
Hi,

the DSC already has security audits and best practice lints for every commit with a zero tolerance policy. One for the jar and one for the docker image.

If you need to perform the security audit again i guess you would need an SBOM in some common format (e.g. SPDX). But this comes with the challenge that the SBOMs for the jars (depending on the feature set) are different from the SBOM for the image.  

What informations do you need?
How should the information supplied?
Have you considered running an analysis on your deployment? This would avoid problems where the documentation does not match the content, and be robust against missing documentation.

**Comment by jmartinezsqs** [comment]
Hello

Thanks for the fast response. 

I would need the SBOM with the technologies used for every possible version of the DSC that can be deployed. We are validating if the technologies being used have active vulnerabilities and in case there are validate if by the implementation these potential vulnerabilities are mitigated.

The information should be supplied in the documentation of the component.

We've also run analysis but we wanted further validation. Would be appreciated to have the information of the tests and analysis run in the component by the development team, that way we can have further information about the current security of the component. We are also validating the documentation so all the functionalities should be correctly reflected in the documentation.

**Comment by brianjahnke** [comment]
Hi,

as just discussed (in a seperate meeting) the (security scanning) information can be found in our CI pipeline under the Action tab for nearly every commit.

**Comment by brianjahnke** [comment]
Hi,
PR #731 will add the SBoM for all docker images. All docker images and SBoMs will be signed.
