### ISSUE TITLE
Admin has no access to root url

### ISSUE THREAD

**Issue by SebastianOpriel** [FraunhoferISST/DataspaceConnector#671]
Hi,
I downloaded current DSC repo and current Messaging Services repo. I updated Messaging Services dependency to use current repo version (5.0.2).
After I start DSC I access `https://localhost:8080/actuator/info` and enter admin credentials. Everything works as expected. 
On switching to root `(https://localhost:8080/)` I get a `There was an unexpected error (type=Forbidden, status=403).`

**Comment by brianjahnke** [comment]
Hi,

I just tried it with the latest release 6.3.1 and the main head. Worked without problems.

**Comment by vdakker** [comment]
I also tried this with the current main DSC and Messaging-Services 5.0.2 and it worked. Tried it with both Firefox and Chrome.

**Comment by SebastianOpriel** [comment]
No longer reproducable. closing
