### ISSUE TITLE
Dataspace Connector v6.1.0 and higher consumer - provider example doesn't work

### ISSUE THREAD

**Issue by nfourlat** [FraunhoferISST/DataspaceConnector#680]
I'm trying to run example for Dataspace Connector in your repository https://github.com/International-Data-Spaces-Association/IDS-Deployment-Examples/tree/main/dataspace-connector/provider-consumer and can't do the simplest request from consumer to provider using swagger: http://localhost:8081/api/ids/description and as recipient: http://provider:8080/api/ids/data. The error I've got is:

provider_1  | 2021-10-11T10:08:20,882 [http-nio-8080-exec-1] ERROR - Failed delivery for (MessageId: 6294D481C68737D-0000000000000000 on ExchangeId: 6294D481C68737D-0000000000000000). Exhausted after delivery attempt: 1 caught: io.dataspaceconnector.service.message.handler.exception.ConnectorOfflineException. Processed by failure processor: FatalFallbackErrorHandler[Channel[direct://handleConnectorOfflineException]]\n\nMessage History (complete message history is disabled)\n---------------------------------------------------------------------------------------------------------------------------------------\nRouteId              ProcessorId          Processor                                                                        Elapsed (ms)\n[descriptionRequest] [descriptionRequest] [                                                                              ] [       151]\n\nStacktrace\n---------------------------------------------------------------------------------------------------------------------------------------\n
provider_1  | io.dataspaceconnector.service.message.handler.exception.ConnectorOfflineException: null
provider_1  |   at io.dataspaceconnector.service.message.handler.validator.OnlineStatusValidator.processInternal(OnlineStatusValidator.java:56) ~[classes!/:6.1.0]
provider_1  |   at io.dataspaceconnector.service.message.handler.validator.OnlineStatusValidator.processInternal(OnlineStatusValidator.java:36) ~[classes!/:6.1.0]
provider_1  |   at io.dataspaceconnector.service.message.handler.validator.base.IdsValidator.process(IdsValidator.java:39) ~[classes!/:6.1.0]
provider_1  |   at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:66) ~[camel-support-3.11.1.jar!/:3.11.1]

**Comment by juliapampus** [comment]
Will update deployment example's `config.json`.
