### ISSUE TITLE
Update artifact data from Swagger UI fails in version 6.2.0

### ISSUE THREAD

**Issue by HariCazorla** [FraunhoferISST/DataspaceConnector#682]
**Describe the bug**
The put request to update the artifact data fails when run from Swagger UI.
After using different header, API works fine from curl command.

**To Reproduce**
- Start an instance of DSC v6.2.0.

- Created an artifact with local data.

- Try to fectch the data using API GET /api/artifacts/{id}/data/ -> Able to fetch it

- Now, try to run API PUT /api/artifacts/{id}/data/ -> Fails with error message
```
edge-connector_1             | 15:37:47.001 [http-nio-8080-exec-4] ERROR io.dataspaceconnector.controller.exceptionhandler.GlobalExceptionHandler - An unhandled exception has been caught. [exception=(Content-Type cannot contain wildcard type '*')]
edge-connector_1             | java.lang.IllegalArgumentException: Content-Type cannot contain wildcard type '*'
edge-connector_1             |  at org.springframework.util.Assert.isTrue(Assert.java:121) ~[spring-core-5.3.9.jar!/:5.3.9]
edge-connector_1             |  at org.springframework.http.HttpHeaders.setContentType(HttpHeaders.java:975) ~[spring-web-5.3.9.jar!/:5.3.9]
edge-connector_1             |  at org.springframework.http.server.ServletServerHttpRequest.getHeaders(ServletServerHttpRequest.java:172) ~[spring-web-5.3.9.jar!/:5.3.9]
```

- Now I tried to run curl command and changed the content type to Application/json and API executes successfully.

``` 
curl -X 'PUT' -u admin:password  'http://localhost:8180/api/artifacts/43330807-8f61-491f-a881-c1b4ff7ce6f9/data'   -H 'accept: */*'   -H 'Content-Type: application/json'   -d '["updated value"]'
```

- Try to fectch the data using API GET /api/artifacts/{id}/data/ -> Able to fetch updated value

**Expected behavior**
Swagger UI configuration needs to be updated to take appropriate headers.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version (DSC) [6.2.0]

**Comment by juliapampus** [comment]
Duplicate of #595

**Comment by juliapampus** [comment]
Duplicate of #595
