### ISSUE TITLE
Unable to publish OR read resource data string in demo application

### ISSUE THREAD

**Issue by Vincent-UBT** [FraunhoferISST/DataspaceConnector#69]
When following the tutorial "Hands-on IDS Communication" using the provided demo application running in Docker, it is not possible to publish a resource data string OR to read this data string.

First, we register a resource through `POST /admin/api/resources/resource` using the Swagger UI running on `localhost:8080/admin`. We use the provided JSON as request body.

Subsequently, we register a corresponding resource representation using `POST /admin/api/resources/{resource-id}/representation`, passing the returned UUID from the previous step. We amended the JSON in the request body as follows:

`{
  "type": "json",
  "byteSize": 105,
  "sourceType": "local",
  "source": {
    "username": "-",
    "password": "-"
  }
}`

Subsequently, we try publishing a resource data string "Test Data" using `PUT /admin/api/resources/{resource-id}/data` passing the previously returned UUID. We receive a 201 Code with the response "Resource published".

However, once we try requesting the data string using `GET /admin/api/resources/{resource-id}/data`, we receive an error 404, telling us "Resource not found".

**Comment by ronjaquensel** [comment]
Hello Vincent,

we where able to reproduce the error. When the data is requested, the url, username and password properties are read from the representation before retrieving the data from the database. As the property url is missing in your representation, this step leads to a NullPointerException. If you modify your representation as follows, you should be able to request the data: 

``{ "type": "json", "byteSize": 105, "sourceType": "local", "source": { "url": "-", "username": "-", "password": "-" } }``

**Comment by juliapampus** [comment]
Hi Vincent, 

we made some changes regarding exception handling and resource input with commit [b75efa94392f2ba70b0468d994417be34a0697cd](https://github.com/FraunhoferISST/DataspaceConnector/tree/b75efa94392f2ba70b0468d994417be34a0697cd). Please take a look at the current version in the dev branch. 

I will close this issue for now. If there are still any problems, please let us know!

**Comment by Vincent-UBT** [comment]
Thank you, this solved our issue.
