### ISSUE TITLE
Nullpointer on artifact.getRepresentations().get(0)

### ISSUE THREAD

**Issue by SebastianOpriel** [FraunhoferISST/DataspaceConnector#698]
Version: latest

After creating 
Catalogue -> Offer/resource -> (cat+offer) -> Representation -> (offer+rep) -> Artifact
I wanted to test, if the artifact is reachable by fetching its data via `artifacts/id/data` path. Obviously the artifact is still detached, without a link to its representation's mediaType. So the ArtifactController throws nullpointer because it accesses the representation object without null-checking in src/main/java/io/dataspaceconnector/controller/resource/type/ArtifactController.java:212

**Comment by brianjahnke** [comment]
Hi,

fixed by 90eb64977821c748b0815dd2c88b1420bcb48c23.
