### ISSUE TITLE
Application.properties DAPS issues

### ISSUE THREAD

**Issue by aitorcelaya** [FraunhoferISST/DataspaceConnector#705]
I have been using the DSC v5.1.2 with the Omejdn DAPS installed locally successfully. I have now installed the DSC v6.3.0 with the Omejdn DAPS and I am having issues with the IDS-Messages.

I will show you my v5.1.2 application.properties and the response we get and then my v6.3.0 application.properties and the responses we get.

DSC v5.1.2 application.properties:
![image](https://user-images.githubusercontent.com/82808687/138091786-1688f202-8917-4d4b-baf3-18927ba4052d.png)

Response (successful DAT using http://omejdn:4567/token):
![image](https://user-images.githubusercontent.com/82808687/138091838-59848bdf-85ba-4e6d-8ac8-1ac3ff474ac2.png)

DSC v6.3.0 application.properties:
![image](https://user-images.githubusercontent.com/82808687/138091952-1970298c-8a9f-4c9a-901f-bb4437feba73.png)

Response (NON-successful DAT using http://omejdn:4567/token):
![image](https://user-images.githubusercontent.com/82808687/138092171-ae66562d-463e-4355-931e-f492411e8467.png)

I attempted changing the "shacl.validation=true" to "false", but it did not help. I am unsure on what "daps.mode" can be changed to other than "aisec" as documentation does not really focus into that "mode".

Thank you in advance.

**Comment by ghost** [comment]
I can't see any error in the settings, the server seems to be reachable but answers with a BAD_REQUEST. So everything should be fine on that settings level.

Unfortunately I am not familiar with the current status of `Omejdn Server`, but there seems to be a three days old PullRequest, which updates the Omejdn server to be able to use it as IDS DAPS. Maybe the opensource Omejdn repo/server has to make some adjustments to make the use case work again. https://github.com/International-Data-Spaces-Association/omejdn-daps/pull/2 @bellebaum

**Comment by ghost** [comment]
The mentioned settings belong to those of the IDS-Messaging-Services by the way and can be found in their documentation:
https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/wiki/09.-Settings:-Connector-Configuration

daps.mode=aisec/orbiter, should be aisec here

**Comment by aitorcelaya** [comment]
Thank you for the clarification and the link to the documentation. I have recreated the scenario with the pre-configured DAPS "https://daps.aisec.fraunhofer.de/v2/token" to make the troubleshooting easier and get rid of other possible issues, such as an external DAPS.

Quick note: I currently have a DSC v6.2.0, had v6.3.0 when I posted this issue. Not a typo.

DSC v6.2.0 application.properties: 
![image](https://user-images.githubusercontent.com/82808687/138238256-fadc6c12-5f71-4806-8bef-4aa6a5d7604e.png)

Response (NON-successful DAT using https://daps.aisec.fraunhofer.de/v2/token):
![image](https://user-images.githubusercontent.com/82808687/138238414-59cd9966-698e-41e8-8dd9-52c5f00e1186.png)

**Comment by ghost** [comment]
In this use-case I'm using different settings (im my testing env.):

![image](https://user-images.githubusercontent.com/75306992/138239375-b42e8d34-39eb-4944-a37e-083f9e68228e.png)

**Comment by ghost** [comment]
In principle there are quite many reasons like an expired or unknown connector certificate for the AISEC DAPS and thus unknown connector fingerprint -> BAD_REQUEST. Unfortunately I don't under which circumstances the DAPS responds with BAD_REQUEST. Perhaps someone from the DAPS would be a better help. @bellebaum

**Comment by bellebaum** [comment]
Omejdn (and thus the DAPS) send out a JSON object describing the the problem for every BAD REQUEST response. Do you have some way to output the response body to diagnose the problem?

**Comment by aitorcelaya** [comment]
Thank you for your inputs.

tmberthold:
I have replicated your setup, as the default v6.2.0 does not include "daps.kid.url=default", but the ERROR still remains. I also temporarily got rid of the "v2" in "daps.key.url" and "daps.key.url.kid" with no luck either.

Regarding the certificate, it is valid and non-expired (Good until 2023). This was provided by Fraunhofer AISEC as seen below:

![image](https://user-images.githubusercontent.com/82808687/138256537-1490a526-f470-416f-8fc4-9d3b1974ba43.png)


bellebaum:
This is the Response body obtained in the Dataspace Connector API with a code 500 error:

![image](https://user-images.githubusercontent.com/82808687/138257068-df9cd998-e9e8-466e-a28d-d62c5a9a25d1.png)

**Comment by bellebaum** [comment]
That is a response that was presumably generated by the Dataspace Connector API.
The response I was looking for comes from the DAPS and should look something like this:

```
{
    "error": "...",
    "error_description": "..."
}
```

**Comment by bellebaum** [comment]
If in doubt, try intercepting network traffic using something like wireshark on your local Omejdn instance. You should see the error response there

**Comment by ghost** [comment]
Next IDS-Messaging-Services version will also log the complete response-body if the request to the DAPS was not successful, could help in the situation.

**Comment by aitorcelaya** [comment]
I managed to find the "error" and "error description" mentioned in the local DAPS setup. There are some issues regarding this:

- If we use the AISEC public DAPS (https://daps.aisec.fraunhofer.de), we have no access to the "error" and "error description" as we have no access at all to the DAPS's side. We can also not use Wireshark as the communication is using TLS.
- If we use the latest Omejdn DAPS version, we are unable to obtain a DAT even with the use of the script in "scripts" folder. We have copied the same setup we had from a previous working Omejdn DAPS and it does NOT work. (I will open an issue in the Omejdn DAPS right after this response here.)
- If we use an older Omejdn DAPS version, I was able to successfully have the v6.2.0 communicate with it.

You can see the application.properties and the DSC v6.2.0's response to this third scenario with an older Omejdn DAPS:

![image](https://user-images.githubusercontent.com/82808687/138668125-461b674b-d1a0-492a-9cf8-e13654a55ebc.png)

The remaining issue now is the default application.properties not being able to reach the DAPS. As per the DSC documentation (Deployment - Configuration), I have changed the following:
1. Changed the config.json from TEST to PRODUCTIVE
2. Added my FH certificate in the /conf directory and replaced keystore-localhost.p12 with {mycert}.p12

**Comment by ghost** [comment]
Hello and thank you for the detailed feedback.

**Omejdn DAPS**
- If there is a problem with the current Omejdn DAPS version, please contact the colleagues directly, if not already done, I think that would be faster.

**Dataspace Connector**
- TEST vs PRODUCTIVE: This setting has no direct effect in this scenario. With the setting of TEST_DEPLOYMENT, IDS-Messages are sent even without a valid DAPS DAT and received messages without a valid DAPS DAT are not rejected with a rejection message. In both cases, PRODUCTIVE and TEST, however, an attempt is made to fetch a DAT from the DAPS. If this fails, no message is sent to e.g. other connectors in PRODUCTIVE_DEPLOYMENT, whereas in TEST_DEPLOYMENT this message is still sent even without a valid DAT. TEST thus enables a quick provider-consumer setup of two connectors to be set up in general test and demo use cases without necessarily having to have a valid DAPS certificate. An overview can be found here: [Connector-Deploy-Modes](https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/wiki/10.-Settings:-Connector-Deploy-Modes)
- If there is a valid DAPS certificate for the connector, it must be specified in the configuration as you described, that is correct. Without a valid DAPS connector certificate, no DAT can be fetched. The default example does not bring a valid certificate out-of-the-box.

**IDS-Messaging-Services**
- The above mentioned functionality to output the complete response of the DAPS in case of errors is now available in the IDS-Messaging-Services v5.1.1 and is already also updated on the Dataspace Connector main branch (snapshot version).

**Comment by ghost** [comment]
E-Mail Quote: _"At the moment, it is possible to successfully receive a DAT from the Omejdn DAPS in PRODUCTIVE_MODE."_
