### ISSUE TITLE
DSC v6.3.2 provider and consumer POST /api/ids/description

### ISSUE THREAD

**Issue by jfernandezsqs** [FraunhoferISST/DataspaceConnector#708]
I am trying to manage a communication between DSC provider and consumer for a “localhost” setup with the DSC version 6.3.2. I am having problems with the POST /api/ids/description call of the API on consumer side requesting provider self description.
I have used Fraunhofer certificates, the latest version of the DSC and the following docker-compose file: 
>version: '3.5'
services:
  provider:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:latest
    ports:
      - 8080:8080
    networks:
      - local
    volumes:
      - ./config_provider.json:/config/config.json
      - ./testidsa9.p12:/conf/testidsa9.p12
    environment:
      - SERVER_SSL_ENABLED=false
      - CONFIGURATION_PATH=/config/config.json
    restart: always
  consumer:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:latest
    ports:
      - 8081:8080
    networks:
      - local
    volumes:
      - ./config_consumer.json:/config/config.json
      - ./testidsa10.p12:/conf/testidsa10.p12
    environment:
      - SERVER_SSL_ENABLED=false
      - CONFIGURATION_PATH=/config/config.json
    restart: always
networks:
  local:
    driver: bridge

### PROVIDER steps carried out
>Offer:  POST /api/offers
{
  "title": "Sample Resource",
  "description": "This is an example resource containing weather data.",
  "keywords": [
    "weather",
    "data",
    "sample"
  ],
  "paymentModality": "fixedPrice",
  "publisher": "https://openweathermap.org/",
  "language": "EN",
  "license": "http://opendatacommons.org/licenses/odbl/1.0/",
  "sovereign": "https://openweathermap.org/",
  "endpointDocumentation": "https://example.com",
  "key": "value"
}

http://localhost:8080/api/offers/e0724fbf-fd3a-45a3-969b-dd4ae513cda0
>Catalog: POST /api/catalogs
{"title": "Example Catalog", "description": "This is an example catalog containing weather data"}
http://localhost:8080/api/catalogs/62af5255-3515-42c1-a4a6-838e8cacc1b6

1.	Add the resource to the catalog -> POST /api/catalogs/{id}/offers
>Rule: POST /api/rules
{"title": "Example Rule Provide Access", "description": "This is an example rule containing a provide access usage policy", "value": "{ \"ids\" : \"https://w3id.org/idsa/core/\", \"idsc\" : \"https://w3id.org/idsa/code/\"},\"@type\": \"ids:Permission\", \"@id\": \"https://w3id.org/idsa/autogen/permission/1c680cc6-3d64-4cbe-9508-b32681bc6c33\", \"ids:description\": [ { \"@value\": \"provide-access\", \"@type\": \"http://www.w3.org/2001/XMLSchema#string\" } ], \"ids:title\": [ { \"@value\": \"Allow Data Usage\", \"@type\": \"http://www.w3.org/2001/XMLSchema#string\" } ], \"ids:assignee\": [], \"ids:assigner\": [], \"ids:postDuty\": [], \"ids:constraint\": [], \"ids:action\": [ { \"@id\": \"idsc:USE\" } ], \"ids:preduty\": []}"}

http://localhost:8080/api/rules/6255e3e6-f8ae-45b2-b850-161bbb8efb86
>Contract: POST /api/contracts
{"title": "Contract","description": "This is an example contract","provider": "http://localhost:8080/","start": "2021-10-21T09:23:13.239Z","end": "2023-10-21T09:23:13.239Z"}
} 
http://localhost:8080/api/contracts/263c8c58-2e04-4ed0-b381-2d139451c069
1.	Add the rule to the contract -> POST /api/contracts/{id}/rules
>Artifact: POST /api/artifacts
{"title": "Example Artifact","value": "Hello World","automatedDownload": true} 

http://localhost:8080/api/artifacts/8c8a102d-5eed-4cbd-8563-ff0211f38cba

>Representation: POST /api/representations
{"title": "Example Representation"}

http://localhost:8080/api/representations/afb9fb7b-d99b-48e5-91d9-808edcb0f2e1
1.	Add the artifact to the representation -> POST /api/representations/{id}/artifacts
2.	Add the representation to the resource -> POST /api/offers/{id}/representations
3.	Add the contract to the offer -> POST /api/offers/{id}/contracts

#### Message description: POST /api/ids/description
http://provider:8080/api/ids/data
Element ID empty
Response body: OK
>{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:BaseConnector",
  "@id" : "http://provider.com",
  "ids:version" : "6.3.2-SNAPSHOT",
  "ids:description" : [ {
    "@value" : "IDS Connector with static example resources hosted by the Fraunhofer ISST",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:title" : [ {
    "@value" : "Dataspace Connector",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:hasDefaultEndpoint" : {
    "@type" : "ids:ConnectorEndpoint",
    "@id" : "https://w3id.org/idsa/autogen/connectorEndpoint/4c8ae983-13de-4a7b-af55-1debb0e65777",
    "ids:endpointDocumentation" : [ ],
    "ids:accessURL" : {
      "@id" : "http://provider:8080/api/ids/data"
    },
    "ids:endpointInformation" : [ ]
  },
  "ids:hasEndpoint" : [ ],
  "ids:resourceCatalog" : [ {
    "@type" : "ids:ResourceCatalog",
    "@id" : "http://provider:8080/api/catalogs/62af5255-3515-42c1-a4a6-838e8cacc1b6",
    "ids:offeredResource" : [ ],
    "ids:requestedResource" : [ ]
  } ],
  "ids:hasAgent" : [ ],
  "ids:securityProfile" : {
    "@id" : "https://w3id.org/idsa/code/BASE_SECURITY_PROFILE"
  },
  "ids:extendedGuarantee" : [ ],
  "ids:maintainer" : {
    "@id" : "https://www.isst.fraunhofer.de/"
  },
  "ids:curator" : {
    "@id" : "https://www.isst.fraunhofer.de/"
  },
  "ids:inboundModelVersion" : [ "4.2.0", "4.1.2", "4.2.1", "4.0.0", "4.1.0", "4.2.2", "4.2.3" ],
  "ids:outboundModelVersion" : "4.2.3"
}

#### Message description: POST /api/ids/description
http://provider:8080/api/ids/data
http://provider:8080/api/catalogs/62af5255-3515-42c1-a4a6-838e8cacc1b6
Response body: NOK
I am receiving the following:
 
![image](https://user-images.githubusercontent.com/82888094/138257814-5e45d755-bdde-4f89-905a-9f861fa4f121.png)

This is the response in the terminal of provider DSC:
 
![image](https://user-images.githubusercontent.com/82888094/138257411-aa42e4c3-90b1-4163-92a7-19e646f88ce2.png)

This is the response in the terminal of consumer DSC:
 
![image](https://user-images.githubusercontent.com/82888094/138257427-b1c53d83-501b-4135-abc5-4f2a0522998c.png)

I am not obtaining the offered resource of the provider DSC, so I am not able of doing Step 2: Query Provider - Request Resource Metadata 
https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/Consumer#step-2-query-provider---request-resource-metadata
Is there something wrong with my deployment or the followed steps? Or is it a problem with this version of the DSC?
Thanks in advance,

**Comment by brianjahnke** [comment]
Hi,
there is no v6.3.2. The latest version is v6.3.1.
-> [Registry](https://github.com/International-Data-Spaces-Association/DataspaceConnector/pkgs/container/dataspace-connector)

**Comment by jfernandezsqs** [comment]
Hi,
I am using the latest version of the DSC available at [https://github.com/International-Data-Spaces-Association/DataspaceConnector.git]
![image](https://user-images.githubusercontent.com/82888094/138276347-e718b9e9-3016-4984-95b3-b503686bab7a.png)
And this shows the API of the DSC.
![image](https://user-images.githubusercontent.com/82888094/138276502-5fee2196-4124-4e2d-8661-ef1d6ac67fa1.png)

**Comment by juliapampus** [comment]
Please use our official Docker image v6.5.0. Does the problem still exist?
