### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by dadebuch** [FraunhoferISST/DataspaceConnector#741]
**Describe the bug**
The connector fetches a token but then throws a javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

**To Reproduce**
1. Deploy two connectors instances and a DAPS in a docker environment
2. Generate a DAPS certificate/key and use the omejdn script Register_connector.sh to generate two certificates for the connectors
3. Use the generated certificates to create a keystore/truststore for both the connector
4. Try to establish a communication in PRODUCTIVE_DEPLOYMENT

**Expected behavior**
The DAPS should be validated and the connection should establish

**Screenshots & Logs**
![SSL_Error](https://user-images.githubusercontent.com/34966289/141087278-4d57c3cd-f758-4c72-a987-96f3c1167d25.JPG)

dataspaceconnector-producer  | Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
dataspaceconnector-producer  |  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439) ~[?:?]
dataspaceconnector-producer  |  at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
dataspaceconnector-producer  |  at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
dataspaceconnector-producer  |  at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313) ~[?:?]
dataspaceconnector-producer  |  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:233) ~[?:?]
dataspaceconnector-producer  |  at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:110) ~[?:?]
dataspaceconnector-producer  |  at de.fraunhofer.ids.messaging.core.config.ssl.truststore.TrustStoreManager$1.checkServerTrusted(TrustStoreManager.java:98) ~[core-5.0.0.jar!/:?]
dataspaceconnector-producer  |  at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1510) ~[?:?]
dataspaceconnector-producer  |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) ~[?:?]
dataspaceconnector-producer  |  ... 139 more
dataspaceconnector-producer  | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
dataspaceconnector-producer  |  at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:?]
dataspaceconnector-producer  |  at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:?]
dataspaceconnector-producer  |  at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
dataspaceconnector-producer  |  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[?:?]
dataspaceconnector-producer  |  at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
dataspaceconnector-producer  |  at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
dataspaceconnector-producer  |  at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313) ~[?:?]
dataspaceconnector-producer  |  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:233) ~[?:?]
dataspaceconnector-producer  |  at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:110) ~[?:?]
dataspaceconnector-producer  |  at de.fraunhofer.ids.messaging.core.config.ssl.truststore.TrustStoreManager$1.checkServerTrusted(TrustStoreManager.java:98) ~[core-5.0.0.jar!/:?]
dataspaceconnector-producer  |  at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1510) ~[?:?]
dataspaceconnector-producer  |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) ~[?:?]
dataspaceconnector-producer  |  ... 139 more

**Additional context**
I tried to add the DAPS certificate to both connectors keystore/truststore but the error persists. 
The self signed certificates are fine as the TLS connection in TEST_DEPLOYMENT works fine, it seems that the connector is unable to verify the received DAT as it won't find any certificate/public key to do so.

Thanks for any response

**Comment by ghost** [comment]
Hi, in the case described there is no problem with the DAPS or the DAT as the DAT was successfully received.

According to the logs, the dataspace-consumer cannot be reached, which is due to a non-valid TLS certificate for HTTPS. The TEST_DEPLOYMENT accepts all TLS certificates, whereas in the PRODUCTIVE_DEPLOYMENT they are validated against the truststore. The TLS certificates of the connectors would have to be added once with matching DNS docker-container names entry in the respective truststores of the other connectors.

More details on TEST_DEPLOYMENT vs PRODUCTIVE_DEPLOYMENT: https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/wiki/10.-Settings:-Connector-Deploy-Modes

**Comment by dadebuch** [comment]
I produced two new certificates specifying: 

SubjectAlternativeName [
  DNSName: dataspaceconnector-producer
]

SubjectAlternativeName [
  DNSName: dataspaceconnector-consumer
]

Then i created the keystores and truststores (e.g. in the consumer's truststore i added the producer.cert).
I guess that the consumer is not able to verify the producer?
When trying to request the description from producer to consumer the connection is refused:

![producer_refused](https://user-images.githubusercontent.com/34966289/141125453-5d9ba439-475c-441b-8ffc-ba397058bc24.JPG)

Trying to do the opposite, so from the consumer to the producer:
![consumer_refused](https://user-images.githubusercontent.com/34966289/141125516-ed4938c3-8a02-4009-b71f-e041893df71d.JPG)

So why would the consumer refuse the connection if the producer does not? I inspected the truststores entries and the docker aliases, everything seems fine.


Edit: this is for example the truststore of the consumer

Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: producer
Creation date: 10 nov 2021
Entry type: trustedCertEntry

Owner: O=Internet Widgits Pty Ltd, ST=Some-State, C=AU
Issuer: O=Internet Widgits Pty Ltd, ST=Some-State, C=AU
Serial number: 1df3103cfbb215c39f965299d692d311bd648ff2
Valid from: Wed Nov 10 14:14:45 CET 2021 until: Sat Nov 08 14:14:45 CET 2031
Certificate fingerprints:
         SHA1: 84:69:98:2A:0E:35:D1:AA:00:D3:DF:96:C0:42:A7:65:0D:B5:C9:F4
         SHA256: 2B:4D:DD:E9:BA:07:31:BA:34:D4:F6:8D:C4:69:98:EA:26:6E:68:00:A9:02:39:2D:88:8B:53:3F:EF:E6:C4:ED
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

1: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 36 61 D3 84 3E 17 0E 85   34 87 8F 1B 52 FE B3 73  6a..>...4...R..s
0010: 1B CE 05 85                                        ....
]
]

2: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

3: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: dataspaceconnector-producer
]

4: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 36 61 D3 84 3E 17 0E 85   34 87 8F 1B 52 FE B3 73  6a..>...4...R..s
0010: 1B CE 05 85                                        ....
]
]

**Comment by ghost** [comment]
Hello and sorry for the late feedback.
I took a closer look at the two screenshots, mostly the error messages go in the following direction:

Screenshot 1: the target container cannot be reached
Screenshot 2: target container can be reached but the TLS certificate for HTTPS is not yet found in the truststore for the requested hostname (container name in this case)

For more debugging details, we would need a closer insight look into the local setup and the further circumstances, as apparently something doesn't quite fit with the setup yet. If we can support here, please just let us know.

**Comment by juliapampus** [comment]
Is this issue solved? @dadebuch
