### ISSUE TITLE
Provider-Consumer-example stops working with DSC version 6.5.0 problably because of contract date range

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#746]
The provider-consumer-example stops working with DSC version 6.5.0.

When trying to negotiate an agreement, the consumer gets the following response from the provider:
```
{"reason":{"properties":null,"@id":"https://w3id.org/idsa/code/NOT_FOUND"},"payload":"Could not find any matching contract offers for your request.","type":"de.fraunhofer.iais.eis.RejectionMessageImpl"}
```
I read about the start and end date validation in the release notes.
I checked the contracts on the provider side. The contract looks like this:
```
{
  "_embedded": {
    "contracts": [
      {
        "creationDate": "2021-11-18T12:51:58.601+0000",
        "modificationDate": "2021-11-18T12:51:58.601+0000",
        "title": "",
        "description": "",
        "start": "2021-11-18T12:51:58.598+0000",
        "end": "2021-11-18T12:51:58.598+0000",
...
```
I assume that the date ranges are not valid. I tried to fix this by setting a date like this in my bootstrap.jsonld
```
"ids:contractOffer": [
        {
          "@type": "ids:ContractOffer",
          "@id": "https://w3id.org/idsa/autogen/contractOffer/1d982c8a-c5ae-4c19-9a26-6815e9540fc8",
          "ids:start": "2021-11-18T12:37:18.417+0000",
          "ids:end": "2099-11-18T12:37:18.417+0000",
          "ids:permission": [
            {
            "@type": "ids:Permission",
            "@id": "https://w3id.org/idsa/autogen/permission/cf1cb758-b96d-4486-b0a7-f3ac0e289588",
            "ids:start": "2021-11-18T12:37:18.417+0000",
            "ids:end": "2099-11-18T12:37:18.417+0000",
```

But this has no effect. I couldn't find an example in the docs about how to set the date of a contract. Could you please update the docs.

**Comment by sebplorenz** [comment]
I read about contractStart and contractEnd in the Infomodel and tried:
```
"ids:contractOffer": [
        {
          "@type": "ids:ContractOffer",
          "@id": "https://w3id.org/idsa/autogen/contractOffer/1d982c8a-c5ae-4c19-9a26-6815e9540fc8",
          "ids:contractStart": "2021-11-18T12:37:18.417+0000",
          "ids:contractEnd": "2021-11-18T12:37:18.417+0000",
...
```
But this leads to the following error:
```
Caused by: java.text.ParseException: Unparseable date: "2021-11-18T12:37:18.417+0000"
        at java.text.DateFormat.parse(DateFormat.java:395) ~[?:?]
```
This is the same date format that the contract endpoint of the API returns. But it is not able to consume it.

It is good that the infomodel parser logs an error if the date format is wrong (as above). But it would be even better if it would log the expected format too. Then a user would be able to fix this error.

**Comment by sebplorenz** [comment]
I still have no clue why the example is not working. Anyone else?

**Comment by juliapampus** [comment]
This is a DSC contract using `ZonedDateTime`:
```
{
  "_embedded": {
    "contracts": [
      {
        "creationDate": "2021-11-18T12:51:58.601+0000",
        "modificationDate": "2021-11-18T12:51:58.601+0000",
        "title": "",
        "description": "",
        "start": "2021-11-18T12:51:58.598+0000",
        "end": "2021-11-18T12:51:58.598+0000",
...
```

The `bootstrap.jsonld` expects valid IDS Infomodel. Thus, the date time value has to be of type `XMLGregorianCalendar`, e.g. `2021-05-17T18:58:39.626Z`. Can you try that?

**Comment by sebplorenz** [comment]
Yes, works. Thank you.
