### ISSUE TITLE
DataspaceConnector version 6.5.1 not compatible with 6.1.3

### ISSUE THREAD

**Issue by edgardmarx** [FraunhoferISST/DataspaceConnector#750]
**Describe the bug**
DataspaceConnector version 6.5.1 cannot communicate with connectors version 6.1.3 which are being used by the DRM Broker

**To Reproduce**
Run Connector version 6.5.1  and try to list resources in a connector 6.1.3 using messages/description API.

**Expected behavior**
Be compatible.

**Screenshots & Logs**

`2021-11-19T13:35:34,785 [http-nio-8080-exec-3] INFO - Sending request to https://ids.dwd-connector.test.mobilitydataspace.io/api/ids/data ...
2021-11-19T13:35:35,217 [http-nio-8080-exec-3] WARN - Received response but response-code not in 200-299. [code=(IMSMEW0046), response-code=(400)]
2021-11-19T13:35:35,255 [http-nio-8080-exec-3] INFO - Successfully passed SHACL-Validation.
2021-11-19T13:35:35,387 [http-nio-8080-exec-3] WARN - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/VERSION_NOT_SUPPORTED, payload=Infomodel Version of incoming Message n
ot supported!, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]`

**Comment by brianjahnke** [comment]
Hi,

version 7.5.1?

**Comment by edgardmarx** [comment]
> Hi,
> 
> version 7.5.1?

sorry, you were faster than I, hope people find my ticket as fast as you and follow my suggestion.

**Comment by ghost** [comment]
Newer versions of the Dataspace Connector support the application.properties setting `infomodel.compatibility.validation=true/false` which is true by default if not set. Disables infomodel-compatibility validation of incoming messages. Could be set to false here.

**Comment by edgardmarx** [comment]
same error:

`
021-11-19T13:58:12,685 [http-nio-8080-exec-6] DEBUG - Built request message. [body=(okhttp3.MultipartBody@63ae289b)]
2021-11-19T13:58:12,687 [http-nio-8080-exec-6] INFO - Sending request to https://ids.dwd-connector.test.mobilitydataspace.io/api/ids/data ...
2021-11-19T13:58:12,930 [http-nio-8080-exec-6] WARN - Received response but response-code not in 200-299. [code=(IMSMEW0046), response-code=(400)]
2021-11-19T13:58:12,982 [http-nio-8080-exec-6] INFO - Successfully passed SHACL-Validation.
2021-11-19T13:58:13,178 [http-nio-8080-exec-6] WARN - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/VERSION_NOT_SUPPORTED, payload=Infomodel Version of incoming Message n
ot supported!, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]
`

**Comment by edgardmarx** [comment]
> same error:
> 
> `021-11-19T13:58:12,685 [http-nio-8080-exec-6] DEBUG - Built request message. [body=(okhttp3.MultipartBody@63ae289b)] 2021-11-19T13:58:12,687 [http-nio-8080-exec-6] INFO - Sending request to https://ids.dwd-connector.test.mobilitydataspace.io/api/ids/data ... 2021-11-19T13:58:12,930 [http-nio-8080-exec-6] WARN - Received response but response-code not in 200-299. [code=(IMSMEW0046), response-code=(400)] 2021-11-19T13:58:12,982 [http-nio-8080-exec-6] INFO - Successfully passed SHACL-Validation. 2021-11-19T13:58:13,178 [http-nio-8080-exec-6] WARN - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/VERSION_NOT_SUPPORTED, payload=Infomodel Version of incoming Message n ot supported!, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]`

same error:

`
021-11-19T13:58:12,685 [http-nio-8080-exec-6] DEBUG - Built request message. [body=(okhttp3.MultipartBody@63ae289b)] 2021-11-19T13:58:12,687 [http-nio-8080-exec-6] INFO - Sending request to https://ids.dwd-connector.test.mobilitydataspace.io/api/ids/data ... 2021-11-19T13:58:12,930 [http-nio-8080-exec-6] WARN - Received response but response-code not in 200-299. [code=(IMSMEW0046), response-code=(400)] 2021-11-19T13:58:12,982 [http-nio-8080-exec-6] INFO - Successfully passed SHACL-Validation. 2021-11-19T13:58:13,178 [http-nio-8080-exec-6] WARN - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/VERSION_NOT_SUPPORTED, payload=Infomodel Version of incoming Message n ot supported!, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]
`

**Comment by edgardmarx** [comment]
> Newer versions of the Dataspace Connector support the application.properties setting `infomodel.compatibility.validation=true/false` which is true by default if not set. Disables infomodel-compatibility validation of incoming messages. Could be set to false here.

**Comment by ghost** [comment]
Just checked, the app.props settings is (here unfortunately) supported as of Dataspace Connector version 6.3.0. Would need to be set on both sides to not validate incoming requests and responses for infomodel compatibility.

You could use the older solution of wildcards in the connector configuration for the inbound modelversion of the v6.1.3 connector, which indicates which infomodel versions are supported for incoming messages. E.g. setting it to `4.*.*`

**Comment by juliapampus** [comment]
The inbound model versions of both DSCs should support the outbound model versions of the other one. Just change the `config.json` accordingly and it will work again.

**Comment by juliapampus** [comment]
> sorry, you were faster than I, hope people find my ticket as fast as you and follow my suggestion.

It's nice to see that people appreciate our support by creating cheeky issues. Drinking enough water is supposed to help against a headache :)
