### ISSUE TITLE
Do not publish DB port in docker-compose

### ISSUE THREAD

**Issue by SebastianOpriel** [FraunhoferISST/DataspaceConnector#751]
Hi, 
as the connector just uses the database internally and all apps shall route the traffic via the connector's APIs (instead of accessing the db) you might close the port. The db shall just be accessible via the network of the connector (e.g., `spring.datasource.url=jdbc:postgresql://postgres:5432/postgres`. Publishing the port might be a security vulnerability. 
See: https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/d90105e0450998db7e7b71e942eb05091301c525/docker-compose.yml#L24

**Comment by brianjahnke** [comment]
Hi,

the docker-compose file is for testing and debugging not productive setups. It is also the reason why the image is build and not just downloaded.
