### ISSUE TITLE
Swagger UI is giving following error

### ISSUE THREAD

**Issue by NehaThawani44** [FraunhoferISST/DataspaceConnector#762]
![image](https://user-images.githubusercontent.com/8424093/143487534-8720e08c-1eeb-4031-a5b6-88cec845e7ff.png)

**Comment by juliapampus** [comment]
Is this still an issue? On what request do you see this error?

**Comment by NehaThawani44** [comment]
Have you changed anytging ? if no then it still might be an issue.

**Comment by juliapampus** [comment]
Again, at what request do you see this error? `/api/docs`? This works for me, I just tested. And what version do you use?

**Comment by NehaThawani44** [comment]
I pulled the latest code on the day I  logged this issue.
