### ISSUE TITLE
Error 500 when requesting another connector's description

### ISSUE THREAD

**Issue by Vincent-UBT** [FraunhoferISST/DataspaceConnector#79]
Dear DataspaceConnector-Team,

we've setup two connectors on a server. After succesfully registering a data resource and corresponding representation on one, we tried accessing it from the other one (which runs on another port). First, we tried requesting the connector's description using POST/admin/api/request/description, passing the url http://{ip-address}:{port}/api/ids/data. We configured the relevant files in the repository for http to work.

This worked in older versions. With the latest commit however, we obtain an error message in the response body:

`Failed to send description request message.`

Did anyone else encounter this yet?

**Comment by brianjahnke** [comment]
Hello Vincent,

we also encountered the problem and commitet a fix (a87fa468ad21ad8da15bc72a923d8c5181648d7c). Please check if the fix solves your problem.
