### ISSUE TITLE
Fail to connect to Clearing House (Log message not send)

### ISSUE THREAD

**Issue by jfernandezsqs** [FraunhoferISST/DataspaceConnector#794]
I have two DSC v6.2.0 Connector A acting as provider and Connector B acting as consumer.
I have an error when the DSC A acting tries to send log message to the Clearing House service. I obtain a message in the logs specifying the following
“WARN - Message handling or processing failed. [exception=(Failed to connect to localhost/127.0.0.1:9999)]”
“WARN - Failed to send log message. [exception=(Message handling or processing failed.)]”
“WARN - Failed to send contract agreement to clearing house. [exception=(Log message could not be sent.)]”

The application.properties file for the clearing.house.url of connector A and B are:
clearing.house.url=http://localhost:9999/messages/log/
I have done all the negotiation process from connector B acting as consumer to connector A acting as provider. I receive the following response body with the POST /api/ids/contract

>{
"creationDate": "2021-12-14T14:45:05.079+0000",
"modificationDate": "2021-12-14T14:45:05.079+0000",
"remoteId": "https://connectora:7000/api/agreements/44645e6d-95ea-46c7-b88f-0f95a1872aaf",
"confirmed": true,
"value": "{\n "@context" : {\n "ids" : "https://w3id.org/idsa/core/\",\n "idsc" : "https://w3id.org/idsa/code/\"\n },\n "@type" : "ids:ContractAgreement",\n "@id" : "https://connectora:7000/api/agreements/44645e6d-95ea-46c7-b88f-0f95a1872aaf\",\n "ids:provider" : {\n "@id" : "https://connector_A"\n },\n "ids:permission" : [ {\n "@type" : "ids:Permission",\n "@id" : "https://connectora:7000/api/rules/fd9bf8e2-f7e6-4578-899c-a48bb3012881",\n "ids:description" : [ {\n "@value" : "provide-access",\n "@type" : "http://www.w3.org/2001/XMLSchema#string"\n } ],\n "ids:title" : [ {\n "@value" : "Allow Data Usage",\n "@type" : "http://www.w3.org/2001/XMLSchema#string"\n } ],\n "ids:assignee" : [ {\n "@id" : "https://connector_B"\n } ],\n "ids:assigner" : [ {\n "@id" : "https://connector_A"\n } ],\n "ids:postDuty" : [ ],\n "ids:action" : [ {\n "@id" : "https://w3id.org/idsa/code/USE"\n } ],\n "ids:constraint" : [ ],\n "ids:preDuty" : [ ],\n "ids:target" : {\n "@id" : "https://connectora:7000/api/artifacts/2df83600-b668-484e-ad2d-5a9982785094"\n }\n } ],\n "ids:consumer" : {\n "@id" : "https://connector_B"\n },\n "ids:prohibition" : [ ],\n "ids:obligation" : [ ],\n "ids:contractStart" : {\n "@value" : "2021-12-14T14:45:01.677Z",\n "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp\"\n },\n "ids:contractDate" : {\n "@value" : "2021-12-14T14:45:01.676Z",\n "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp\"\n }\n}",
"_links": {
"self": {
"href": "https://localhost:7001/api/agreements/58c42be5-5879-43d0-87d9-4ace0634ad99"
},
"artifacts": {
"href": "https://localhost:7001/api/agreements/58c42be5-5879-43d0-87d9-4ace0634ad99/artifacts{?page,size}",
"templated": true
}}}

This is the docker-compose .yml file I am using for the Clearing House:
[docker-compose.yml.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7712714/docker-compose.yml.docx)

I attach also the logs obtained from the Connector A, connector B and the Clearing House logs.
[ConnectorA_logs.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7712675/ConnectorA_logs.docx)
[ConnectorB_logs.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7712677/ConnectorB_logs.docx)
[ClearingHouse_logs.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7712678/ClearingHouse_logs.docx)

I have also tried changing the clearing.house.url with the following configuration:

>clearing.house.url=http://localhost:9999/

but it is still showing the same error.

I do not know how to proceed with this WARN message that blocks me from sending the logs to the CH.
Do you know what is the problem or how to fix this issue?
I will post also this issue at the Clearing House repository so that I can obtain help from them also.
Thanks in advance,

**Comment by ghost** [comment]
`Failed to connect to localhost/127.0.0.1:9999` Since it looks like the two connectors are started as Docker containers and also the Clearinghouse as a Docker container, given its docker-compose, could you try using a Clearinghouse container name in the URL of the Clearinghouse instead of `localhost`?

**Comment by jfernandezsqs** [comment]
I have changed the application.properties files of ConnectorA and ConnectorB to:
>clearing.house.url=http://testidsa12:9999/messages/log/

changing the container name of the trusted connector to testidsa12 in the docker-compose.yml
I have also introduced the testidsa12.crt in the truststore.p12 and placed in the clients.yml of the DAPS the testidsa12.cert
These are the logs I am obtaining:
[ConnectorA_logs.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7719144/ConnectorA_logs.docx)
[ConnectorB_logs.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7719145/ConnectorB_logs.docx)
[ClearingHouse_logs.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7719146/ClearingHouse_logs.docx)

In the CH logs it appears the following error:
![image](https://user-images.githubusercontent.com/82888094/146183774-725fff8f-88fc-453f-b8c1-6f1c0b04197e.png)
And at the ConnectorA logs: 
![image](https://user-images.githubusercontent.com/82888094/146183954-bf4f94ee-ce49-4f54-91c4-2f4583d4ac27.png)

I think it is neccesary to change the pointing DAPS of the trusted connector but I do not know how to do this.
And also I do not know if this is the reason of the error.

**Comment by ghost** [comment]
In the first step, this looks good, because it shows that the ClearingHouse container can now be reached when using its container name instead of localhost in the ClearingHouse URL.

Next problem:
The ClearingHouse now responds to the Dataspace Connector with a response using a status-code 500 (internal server error).

Possible Cause:
The logs from the ClearingHouse and the response-log of the Dataspace Connector indicate that the ClearingHouse failed in its attempt to retrieve a DAT from the DAPS because it cannot find the DAPS (404 not found).

I can't help at that point though, I'll note that in the other issue.
_(if anyone reads this who knows about the ClearingHouse configuration, feel free to help here)_

**Comment by kragall** [comment]
From the error message in the Clearing House log I get the impression that there is a versioning problem between the clearing-house-service and the clearing-house-core versions you are using. Can you check that you are indeed using a container that was built with the newest version of clearing-house-service?

The clearing-house-core obviously uses the newly introduced jwks cache feature, while the service seems to fail to provide the required caching variables. If you do not need the newest features, it might be a good idea to use the release tags v0.7.1 and v0.7.2.

**Comment by jfernandezsqs** [comment]
I have checked that I have the latest versions for core and service.
I have used:
>git clone https://github.com/Fraunhofer-AISEC/ids-clearing-house-core.git
git clone https://github.com/Fraunhofer-AISEC/ids-clearing-house-service.git

I have installed it again with the latest information from the repository but it still gives me the same error.

**Comment by kragall** [comment]
I checked the code again and there is only one place where this specific error message is created. And the only way the code flow might end up there is if line 45 of [`clearing-house-app/clearing-house-api/src/main.rs`](https://github.com/Fraunhofer-AISEC/ids-clearing-house-service/blob/master/clearing-house-app/clearing-house-api/src/main.rs) is missing. So please check that in your checked out version of `ids-clearing-house-service` the file `clearing-house-app/clearing-house-api/src/main.rs` contains line 45 from the link above.

You can also use either `git pull` to make sure that you have the current version or `git status` which tells you if your branch is up-to-date or not.

**Comment by jfernandezsqs** [comment]
I have just checked it and I have that line specified.
![image](https://user-images.githubusercontent.com/82888094/146334298-22936a01-bfc6-49ad-bfd2-cfab8f6c920a.png)

**Comment by kragall** [comment]
Using the latest version of both clearing-house-service and clearing-house-core I cannot reproduce the error. However, if I use an older version of clearing-house-service (e.g. v0.7.1) then I get the same error.

As such, please do the following:
1. Change to directory `ids-clearing-house-service/clearing-house-app/clearing-house-api`
2. Run `cargo clean`
3. Run `cargo build`
4. Change to the directory `ids-clearing-house-service/`
5. Build the docker container using a new unique tag, e.g. by using `docker build -f docker/clearing-house-api-multistage.Dockerfile . -t sqs-ch-latest`
6. Change docker-compose.yml to use the new image of `clearing-house-api`

**Comment by jfernandezsqs** [comment]
Update:
https://github.com/Fraunhofer-AISEC/ids-clearing-house-service/issues/5

**Comment by juliapampus** [comment]
Is this issue solved?

**Comment by ghost** [comment]
No - however we cannot do anything here in our world.
https://github.com/industrial-data-space/idscp2-java/issues/7

_ClearingHouse-container can't connect to the omejdn-container because hardcoded url-ending in a lib._

**Comment by juliapampus** [comment]
Okay, as this issue is now linked, I will close it here.
