### ISSUE TITLE
N-times Usage policy negotiation error

### ISSUE THREAD

**Issue by jfernandezsqs** [FraunhoferISST/DataspaceConnector#795]
I have deployed two DSC v6.2.0 (ConnectorA acting as provider) and ConnectorB (acting as consumer) and I am trying to do the negotiation between them, but I am having some issues. I have been able of doing all the negotiation for the PROVIDE_ACCESS usage policy, but when I try with the N-times usage policy I do not obtain the artifact, rule and offer of the Connector A (provider).
Following the documentation, I have obtained a usage policy for N times Usage:
POST /api/examples/policy
![image](https://user-images.githubusercontent.com/82888094/146043630-8f8a312b-f8bd-49c4-a57e-021345a51923.png)
This is the response body I obtain:
>{
  "@context" : {
    "xsd" : "http://www.w3.org/2001/XMLSchema#",
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:Permission",
  "@id" : "https://w3id.org/idsa/autogen/permission/6e7832ea-0588-4d85-b94a-016eb5ad4184",
  "ids:description" : [ {
    "@value" : "n-times-usage",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:postDuty" : [ ],
  "ids:title" : [ {
    "@value" : "Example Usage Policy",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:assignee" : [ ],
  "ids:assigner" : [ ],
  "ids:action" : [ {
    "@id" : "https://w3id.org/idsa/code/USE"
  } ],
  "ids:constraint" : [ {
    "@type" : "ids:Constraint",
    "@id" : "https://w3id.org/idsa/autogen/constraint/67671c4b-7c0d-4d8b-9abe-2fbe05ede8bd",
    "ids:operator" : {
      "@id" : "https://w3id.org/idsa/code/LTEQ"
    },
    "ids:leftOperand" : {
      "@id" : "https://w3id.org/idsa/code/COUNT"
    },
    "ids:rightOperand" : {
      "@value" : "5",
      "@type" : "xsd:double"
    }
  } ],
  "ids:preDuty" : [ ]
}

I noted that this is not exactly the usage policy for N times usage that appears in the documentation. 
(https://international-data-spaces-association.github.io/DataspaceConnector/Documentation/v6/UsageControl#n-times-usage-1)
With this response body I created the following rule:
POST /api/rules
>{"title": "[\"N times Usage\"^^http://www.w3.org/2001/XMLSchema#string]",
   "description": "", 
"value":"{\n    \"@context\" : {\n    \"xsd\" : \"http://www.w3.org/2001/XMLSchema#\",\n    \"ids\" : \"https://w3id.org/idsa/core/\",\n    \"idsc\" : \"https://w3id.org/idsa/code/\"\n  },\n  \"@type\" : \"ids:Permission\",\n  \"@id\" : \"https://w3id.org/idsa/autogen/permission/6e7832ea-0588-4d85-b94a-016eb5ad4184\",\n  \"ids:description\" : [ {\n    \"@value\" : \"n-times-usage\",\n    \"@type\" : \"http://www.w3.org/2001/XMLSchema#string\"\n  } ],\n    \"ids:postDuty\" : [ ],\n    \"ids:title\" : [ {\n    \"@value\" : \"Example Usage Policy\",\n    \"@type\" : \"http://www.w3.org/2001/XMLSchema#string\"\n  } ],\n    \"ids:assignee\" : [ ],\n  \"ids:assigner\" : [ ],\n    \"ids:action\" : [ {\n    \"@id\" : \" https://w3id.org/idsa/code/USE \"\n  } ],\n    \"ids:constraint\" : [ {\n    \"@type\" : \"ids:Constraint\",\n    \"@id\" : \"https://w3id.org/idsa/autogen/constraint/67671c4b-7c0d-4d8b-9abe-2fbe05ede8bd\",\n    \"ids:operator\" : {\n    \"@id\" : \" https://w3id.org/idsa/code/LTEQ\"\n },\n    \"ids:leftOperand\" : {\n   \"@id\" : \"https://w3id.org/idsa/code/COUNT\"\n  },\n    \"ids\" : \"rightOperand\" : {\n    \"@value\" : \"5\",\n    \"@type\" : \"xsd:double\"\n  }\n }],\n    \"ids:preDuty\" : [ ]\n }"}

![image](https://user-images.githubusercontent.com/82888094/146043865-f535d3b4-0ec0-4b49-971b-6e1b69bc8c27.png)
![image](https://user-images.githubusercontent.com/82888094/146043879-d40f9a79-f377-4f1f-b207-3d4b581a9bb4.png)

I have done all the documentation steps for the provider side but when I try to obtain from Connector B the self-description of connector A, I obtain the following response body with no artifact, offer and rule.
![image](https://user-images.githubusercontent.com/82888094/146043916-b3a3d1b5-12de-416f-b970-60ef30674824.png)
With response body:
>{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:BaseConnector",
  "@id" : "https://connector_A",
  "ids:description" : [ {
    "@value" : "IDS Connector A with static example resources",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:version" : "6.2.0",
  "ids:title" : [ {
    "@value" : "Dataspace Connector",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:resourceCatalog" : [ {
    "@type" : "ids:ResourceCatalog",
    "@id" : "https://connectora:8080/api/catalogs/49c8e2a1-b785-459a-af8b-3e733527bf38",
    "ids:offeredResource" : [ ],
    "ids:requestedResource" : [ ]
  } ],
  "ids:hasAgent" : [ ],
  "ids:securityProfile" : {
    "@id" : "https://w3id.org/idsa/code/BASE_SECURITY_PROFILE"
  },
  "ids:extendedGuarantee" : [ ],
  "ids:maintainer" : {
    "@id" : "https://www.isst.fraunhofer.de/"
  },
  "ids:curator" : {
    "@id" : "https://www.isst.fraunhofer.de/"
  },
  "ids:inboundModelVersion" : [ "4.2.0", "4.1.2", "4.0.0", "4.1.0" ],
  "ids:outboundModelVersion" : "4.2.0",
  "ids:publicKey" : {
    "@type" : "ids:PublicKey",
    "@id" : "https://w3id.org/idsa/autogen/publicKey/78eb73a3-3a2a-4626-a0ff-631ab50a00f9",
    "ids:keyType" : {
      "@id" : "https://w3id.org/idsa/code/RSA"
    },
    "ids:keyValue" : "VFVsSlFrbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGUk9FRk5TVWxDUTJkTFEwRlJSVUYxZHpadFJuSmtabXhZV2xSS1owWlBRVFZ6YlVSWVF6QTVVMjF3U2xkdlIzQjVSVkphVGtWNU16RndTMlJ6VWtkb1ZHbHdVakkzYWpscGNtMXRjV2xvZGpkblNXZDZRMjU0Tm10SlVrNUhTVEoxTUc5R1VUVkdaM1pQTVhoNFozcGphV2hrY0VZd1EyaGxUMlk1U1U1bmFYTlFhM0UxYUdvNFFXVXZSRmxZYTNacWFGRTJZelpoYXk5YVdXWnFNRTV3Y1hsRlVHTktOVTFNVW0xWlIyVjRUV0ZOV20xVVluRkVTblpLYkRWS1J6TXJZa1V6V1dFeU1XaFVXbGxQZUdsVGFXTndaa1puU2pNd2EyNDFZVlZKUVhSa01EVkpXbmszZWpGelJHbFdUSFJVV0d4TVptVXZXbEZETkhCdWFrWjBjeXQwWXpFeWMxZzVhV2hKYlc1RGEyUXdWM1o2TTBOVVdtOTVRbE56WXpGVVpFSnJZamx0TUVNMWRIWm5NR1pSVURSUlowWXZla2d5VVc5YWJtNXlTVFV5ZFVGYU9FMXZiVmQwV1RKc2RETkVNR3RyY0ZJMk9YQm1Wa1JLTjNremRrNHZaWGRKUkVGUlFVST0="
  },
  "ids:hasEndpoint" : [ ],
  "ids:hasDefaultEndpoint" : {
    "@type" : "ids:ConnectorEndpoint",
    "@id" : "https://w3id.org/idsa/autogen/connectorEndpoint/e5e2ab04-633a-44b9-87d9-a097ae6da3cf",
    "ids:accessURL" : {
      "@id" : "https://connectora:8080/api/ids/data"
    },
    "ids:endpointDocumentation" : [ ],
    "ids:endpointInformation" : [ ]
  }
}

When I do the call with the catalog I obtain the following:
![image](https://user-images.githubusercontent.com/82888094/146044007-395a3e9d-4ff4-4ba6-b81c-66cd38e4b807.png)
In the logs of the Connector B appears the following error:
![image](https://user-images.githubusercontent.com/82888094/146044085-9fd705b9-5f25-437d-ae96-4a5bd811aac5.png)
I assume that the POST of the rule for N times usage was not correct.
Could you please help me with this issue or provide me with the correct POST/api/rules? 
So that I do not have this issue and I am able of checking the N times usage policy.
I believe that it is necessary to have detailed more clearly in the documentation section
(https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/Provider#providing-data)
 how to perform the different POST /api/rules that are currently supported by the DSC for the different usage policies and also how to create the contract and how to add the contract to the rule.
Thanks in advance,

**Comment by jfernandezsqs** [comment]
I have detected and fixed an error on my usage policy (this is the current Usage policy)
![image](https://user-images.githubusercontent.com/82888094/148762225-f024c502-57c8-4fb5-b3aa-c356ea460e5c.png)
When I try to obtain from Connector B the self-description of connector A, I obtain the following response body with no artifact, offer and rule.
![image](https://user-images.githubusercontent.com/82888094/148762690-0f386a84-343c-4b9d-8c1e-9f4879a7c8a0.png)
I am obtaining a warning at the logs of connector A:
![image](https://user-images.githubusercontent.com/82888094/148762839-74412759-4b7d-4c47-a4bc-6f0ecd5e372d.png)
Could you please help me with this issue?

**Comment by HeinrichPet** [comment]
As the warning says, there is a space in front of USE and LTEQ inside your rule definition.

So try it without the spaces:
> {"title": "["N times Usage"^^http://www.w3.org/2001/XMLSchema#string]",
> "description": "",
> "value":"{\n "@context" : {\n "xsd" : "http://www.w3.org/2001/XMLSchema#\",\n "ids" : "https://w3id.org/idsa/core/\",\n "idsc" : "https://w3id.org/idsa/code/\"\n },\n "@type" : "ids:Permission",\n "@id" : "https://w3id.org/idsa/autogen/permission/6e7832ea-0588-4d85-b94a-016eb5ad4184\",\n "ids:description" : [ {\n "@value" : "n-times-usage",\n "@type" : "http://www.w3.org/2001/XMLSchema#string"\n } ],\n "ids:postDuty" : [ ],\n "ids:title" : [ {\n "@value" : "Example Usage Policy",\n "@type" : "http://www.w3.org/2001/XMLSchema#string"\n } ],\n "ids:assignee" : [ ],\n "ids:assigner" : [ ],\n "ids:action" : [ {\n "@id" : "https://w3id.org/idsa/code/USE"\n } ],\n "ids:constraint" : [ {\n "@type" : "ids:Constraint",\n "@id" : "https://w3id.org/idsa/autogen/constraint/67671c4b-7c0d-4d8b-9abe-2fbe05ede8bd",\n "ids:operator" : {\n "@id" : "https://w3id.org/idsa/code/LTEQ"\n },\n "ids:leftOperand" : {\n "@id" : "https://w3id.org/idsa/code/COUNT"\n },\n "ids" : "rightOperand" : {\n "@value" : "5",\n "@type" : "xsd:double"\n }\n }],\n "ids:preDuty" : [ ]\n }"}

**Comment by jfernandezsqs** [comment]
I have fixed that spaces and when I try to negotiate with the provider I am getting error of MALFORMED MESSAGE.
![image](https://user-images.githubusercontent.com/82888094/148926133-b9118d72-2a4a-4ff9-895b-af8ff782b05b.png)
![image](https://user-images.githubusercontent.com/82888094/148925926-de36c511-ce44-4f8b-a47b-3245202321c4.png)
![image](https://user-images.githubusercontent.com/82888094/148926031-74120654-14c8-4d65-82be-bb72dc4bba86.png)

**Comment by juliapampus** [comment]
In your last image, the permission in the request body seems to be malformed. Context information are missing. Is this the exact rule you get back from the provider on a description request @jfernandezsqs?

**Comment by jfernandezsqs** [comment]
Yes, I have re-executed it doing all the steps at provider connector. This is the description obtained from the consumer:
>{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:ResourceCatalog",
  "@id" : "https://connectora:8080/api/catalogs/b4e51b71-9be7-477a-8a75-5090e678bab3",
  "ids:offeredResource" : [ {
    "@type" : "ids:Resource",
    "@id" : "https://connectora:8080/api/offers/4d587011-1cfe-44d8-922b-62ca3dfcc43d",
    "ids:version" : "1",
    "ids:description" : [ {
      "@value" : "DWD weather warnings for germany.",
      "@language" : "DE"
    } ],
    "ids:language" : [ {
      "@id" : "https://w3id.org/idsa/code/DE"
    } ],
    "ids:title" : [ {
      "@value" : "DWD Weather Warnings",
      "@language" : "DE"
    } ],
    "ids:standardLicense" : {
      "@id" : ""
    },
    "ids:contentPart" : [ ],
    "ids:theme" : [ ],
    "ids:resourcePart" : [ ],
    "ids:representation" : [ {
      "@type" : "ids:Representation",
      "@id" : "https://connectora:8080/api/representations/1b968fb0-9f91-4717-b71a-9d65572f5c47",
      "ids:description" : [ ],
      "ids:mediaType" : {
        "@type" : "ids:IANAMediaType",
        "@id" : "https://w3id.org/idsa/autogen/iANAMediaType/5156f2a4-9a49-4382-80d8-a0b872975285",
        "ids:filenameExtension" : "json"
      },
      "ids:language" : {
        "@id" : "https://w3id.org/idsa/code/EN"
      },
      "ids:title" : [ ],
      "ids:representationStandard" : {
        "@id" : ""
      },
      "ids:created" : {
        "@value" : "2022-01-19T09:49:38.140Z",
        "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
      },
      "ids:modified" : {
        "@value" : "2022-01-19T09:49:38.140Z",
        "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
      },
      "ids:instance" : [ {
        "@type" : "ids:Artifact",
        "@id" : "https://connectora:8080/api/artifacts/87c422fa-5eb8-461f-af0c-3ec6c5da0182",
        "ids:fileName" : "Hello world json test",
        "ids:creationDate" : {
          "@value" : "2022-01-19T09:49:36.903Z",
          "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
        },
        "ids:byteSize" : 0,
        "ids:checkSum" : "0"
      } ]
    } ],
    "ids:defaultRepresentation" : [ ],
    "ids:publisher" : {
      "@id" : "https://dwd.com"
    },
    "ids:sovereign" : {
      "@id" : "https://dwd.com"
    },
    "ids:resourceEndpoint" : [ {
      "@type" : "ids:ConnectorEndpoint",
      "@id" : "https://w3id.org/idsa/autogen/connectorEndpoint/3e5c154e-69a2-4462-8039-eb62bed37508",
      "ids:accessURL" : {
        "@id" : "https://connectora:8080/api/offers/4d587011-1cfe-44d8-922b-62ca3dfcc43d"
      },
      "ids:endpointDocumentation" : [ {
        "@id" : ""
      } ],
      "ids:endpointInformation" : [ ]
    } ],
    "ids:contractOffer" : [ {
      "@type" : "ids:ContractOffer",
      "@id" : "https://connectora:8080/api/contracts/a31fea74-81f3-49d9-b5f2-c90b2a3da6c5",
      "ids:provider" : {
        "@id" : "https://connectora:8080/"
      },
      "ids:permission" : [ {
        "@type" : "ids:Permission",
        "@id" : "https://connectora:8080/api/rules/351f216b-0ce1-4101-b854-e84291c6ddfb",
        "ids:description" : [ {
          "@value" : "n-times-usage",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:title" : [ {
          "@value" : "Example Usage Policy",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:assignee" : [ ],
        "ids:assigner" : [ ],
        "ids:postDuty" : [ ],
        "ids:action" : [ {
          "@id" : "https://w3id.org/idsa/code/USE"
        } ],
        "ids:preDuty" : [ ],
        "ids:constraint" : [ {
          "@type" : "ids:Constraint",
          "@id" : "https://w3id.org/idsa/autogen/constraint/67671c4b-7c0d-4d8b-9abe-2fbe05ede8bd",
          "ids:leftOperand" : {
            "@id" : "https://w3id.org/idsa/code/COUNT"
          },
          "ids:rightOperand" : {
            "@value" : "2",
            "@type" : "http://www.w3.org/2001/XMLSchema#double"
          },
          "ids:operator" : {
            "@id" : "https://w3id.org/idsa/code/LTEQ"
          }
        } ]
      } ],
      "ids:consumer" : {
        "@id" : ""
      },
      "ids:contractEnd" : {
        "@value" : "2023-10-22T07:48:37.068Z",
        "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
      },
      "ids:contractDate" : {
        "@value" : "2022-01-19T09:50:14.586Z",
        "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
      },
      "ids:contractStart" : {
        "@value" : "2022-01-19T09:49:34.516Z",
        "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
      },
      "ids:obligation" : [ ],
      "ids:prohibition" : [ ]
    } ],
    "ids:created" : {
      "@value" : "2022-01-19T09:49:29.141Z",
      "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
    },
    "ids:modified" : {
      "@value" : "2022-01-19T09:49:29.141Z",
      "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
    },
    "ids:temporalCoverage" : [ ],
    "ids:spatialCoverage" : [ ],
    "ids:keyword" : [ {
      "@value" : "DWD",
      "@language" : "DE"
    } ],
    "ids:sample" : [ ]
  } ],
  "ids:requestedResource" : [ ]
}

And this is the contract negotiation:
>curl -X 'POST' \
  'https://localhost:8081/api/ids/contract?recipient=https%3A%2F%2Fconnectora%3A8080%2Fapi%2Fids%2Fdata&resourceIds=https%3A%2F%2Fconnectora%3A8080%2Fapi%2Foffers%2F4d587011-1cfe-44d8-922b-62ca3dfcc43d&artifactIds=https%3A%2F%2Fconnectora%3A8080%2Fapi%2Fartifacts%2F87c422fa-5eb8-461f-af0c-3ec6c5da0182&download=true' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '[ {
        "@type" : "ids:Permission",
        "@id" : "https://connectora:8080/api/rules/351f216b-0ce1-4101-b854-e84291c6ddfb",
        "ids:description" : [ {
          "@value" : "n-times-usage",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:title" : [ {
          "@value" : "Example Usage Policy",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:action" : [ {
          "@id" : "https://w3id.org/idsa/code/USE"
        }],
        "ids:target" : "https://connectora:8080/api/artifacts/87c422fa-5eb8-461f-af0c-3ec6c5da0182"
} ]'

And the response body:
![image](https://user-images.githubusercontent.com/82888094/150108331-19ed0f41-837a-4a41-9616-505e4e2fd0c2.png)

**Comment by juliapampus** [comment]
How did you create the contract? Did you set consumer to an empty string ("")? The DSC compares the set consumer to the connector's id of the incoming message within the negotiation. Maybe you can create a contract with the same contract without the consumer attribute? Only a first guess.

**Comment by jfernandezsqs** [comment]
This is the contract request body I used.
![image](https://user-images.githubusercontent.com/82888094/150123683-6d5adc0d-d342-43cb-8542-9cc7e497b146.png)

**Comment by juliapampus** [comment]
We suspect that the error is caused by escapes or missing ones in the Swagger UI. Could you test the same rule again via the Python script? It should work with that.

**Comment by ronjaquensel** [comment]
Hi, I just tested a contract negotiation with the n-times-usage policy obtained via `POST /api/examples/policy`.

When using the following input to create the rule via the Swagger UI, I can successfully negotiate a contract:
```json
{
  "value": "{\n\"@context\" : {\n\"xsd\" : \"http://www.w3.org/2001/XMLSchema#\",\n\"ids\" : \"https://w3id.org/idsa/core/\",\n\"idsc\" : \"https://w3id.org/idsa/code/\"\n},\n\"@type\" : \"ids:Permission\",\n\"@id\" : \"https://w3id.org/idsa/autogen/permission/447fd9d9-3bad-41d2-84c5-ad3161151fae\",\n\"ids:description\" : [ {\n\"@value\" : \"n-times-usage\",\n\"@type\" : \"http://www.w3.org/2001/XMLSchema#string\"\n} ],\n\"ids:title\" : [ {\n\"@value\" : \"Example Usage Policy\",\n\"@type\" : \"http://www.w3.org/2001/XMLSchema#string\"\n} ],\n\"ids:assignee\" : [ ],\n\"ids:assigner\" : [ ],\n\"ids:postDuty\" : [ ],\n\"ids:action\" : [ {\n\"@id\" : \"https://w3id.org/idsa/code/USE\"\n} ],\n\"ids:constraint\" : [ {\n\"@type\" : \"ids:Constraint\",\n\"@id\" : \"https://w3id.org/idsa/autogen/constraint/d2376f4f-9339-4427-9297-35576bb81e5f\",\n\"ids:leftOperand\" : {\n\"@id\" : \"https://w3id.org/idsa/code/COUNT\"\n},\n\"ids:rightOperand\" : {\n\"@value\" : \"5\",\n\"@type\" : \"xsd:double\"\n},\n\"ids:operator\" : {\n\"@id\" : \"https://w3id.org/idsa/code/LTEQ\"\n}\n} ],\n\"ids:preDuty\" : [ ]\n}"
}
```

**Comment by jfernandezsqs** [comment]
**@ronjaquensel**: Which version of the DSC are you currently using?
I have used version 6.2.0 and for me it is not working.
If it is an update that fix the issue for the actual version, I will test it again when version 7 of the DSC is available.

**Comment by ronjaquensel** [comment]
I tested locally with v6.2.0 and with the Docker image 6.2.0 as well, for me it worked in both cases. Are you using the official tag or have you checked out a specific commit?

**Comment by jfernandezsqs** [comment]
I am using the official tag.

**Comment by jfernandezsqs** [comment]
These are the logs I am obtaining from the Consumer DSC.
![image](https://user-images.githubusercontent.com/82888094/150965950-8900466b-09c2-4f5f-aa53-cf9781da5ac2.png)
And this is the response error obtained from the Swagger UI
![image](https://user-images.githubusercontent.com/82888094/150966041-747f506f-5fd3-470c-bbf0-f964a292e6ea.png)

**Comment by juliapampus** [comment]
Could you try and see if this error still exists with v7?

**Comment by jfernandezsqs** [comment]
I have moved to version 7.0.0 of the DSC.
I used the POST /api/examples/policy
```
{
  "@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "ids": "https://w3id.org/idsa/core/",
    "idsc": "https://w3id.org/idsa/code/"
  },
  "@type": "ids:Permission",
  "@id": "https://w3id.org/idsa/autogen/permission/48db8b34-facd-42bd-a0eb-83e2e841b9f0",
  "ids:description": [
    {
      "@value": "string",
      "@type": "http://www.w3.org/2001/XMLSchema#string"
    }
  ],
  "ids:title": [
    {
      "@value": "string",
      "@type": "http://www.w3.org/2001/XMLSchema#string"
    }
  ],
  "ids:constraint": [
    {
      "@type": "ids:Constraint",
      "@id": "https://w3id.org/idsa/autogen/constraint/43dc89ba-a953-450c-90df-36fbf1f99dd1",
      "ids:leftOperand": {
        "@id": "https://w3id.org/idsa/code/COUNT"
      },
      "ids:rightOperand": {
        "@value": "5",
        "@type": "xsd:double"
      },
      "ids:operator": {
        "@id": "https://w3id.org/idsa/code/LTEQ"
      }
    }
  ],
  "ids:action": [
    {
      "@id": "https://w3id.org/idsa/code/USE"
    }
  ]
}
```
This is the rule created:
```
{
    "title": "[\"N times Usage\"]",
    "description": "", 
    "value": "{\n\"@context\" : {\n\"xsd\" : \"http://www.w3.org/2001/XMLSchema#\",\n\"ids\" : \"https://w3id.org/idsa/core/\",\n\"idsc\" : \"https://w3id.org/idsa/code/\"\n},\n\"@type\" : \"ids:Permission\",\n\"@id\" : \"https://w3id.org/idsa/autogen/permission/48db8b34-facd-42bd-a0eb-83e2e841b9f0\",\n  \"ids:description\" : [ {\n\"@value\" : \"n-times-usage\",\n\"@type\" : \"http://www.w3.org/2001/XMLSchema#string\"\n} ],\n\"ids:title\" : [ {\n\"@value\" : \"ExampleUsagePolicy\",\n\"@type\" : \"http://www.w3.org/2001/XMLSchema#string\"\n} ],\n\"ids:constraint\" : [ {\n\"@type\" : \"ids:Constraint\",\n\"@id\" : \"https://w3id.org/idsa/autogen/constraint/43dc89ba-a953-450c-90df-36fbf1f99dd1\",\n \"ids:leftOperand\" : {\n\"@id\" : \"https://w3id.org/idsa/code/COUNT\"\n},\n \"ids:rightOperand\" : {\n\"@value\" : \"5\",\n\"@type\" : \"xsd:double\"\n},\n \"ids:operator\" : {\n\"@id\" : \"https://w3id.org/idsa/code/LTEQ\"\n}\n }\n],\n \"ids:action\" : [\n {\n \"@id\" : \"https://w3id.org/idsa/code/USE\"\n}\n]\n}"
}
```
and the response body is:
```
{
  "creationDate": "2022-02-07T11:12:08.963+0000",
  "modificationDate": "2022-02-07T11:12:08.963+0000",
  "title": "[\"N times Usage\"]",
  "description": "",
  "value": "{\n\"@context\" : {\n\"xsd\" : \"http://www.w3.org/2001/XMLSchema#\",\n\"ids\" : \"https://w3id.org/idsa/core/\",\n\"idsc\" : \"https://w3id.org/idsa/code/\"\n},\n\"@type\" : \"ids:Permission\",\n\"@id\" : \"https://w3id.org/idsa/autogen/permission/48db8b34-facd-42bd-a0eb-83e2e841b9f0\",\n  \"ids:description\" : [ {\n\"@value\" : \"n-times-usage\",\n\"@type\" : \"http://www.w3.org/2001/XMLSchema#string\"\n} ],\n\"ids:title\" : [ {\n\"@value\" : \"ExampleUsagePolicy\",\n\"@type\" : \"http://www.w3.org/2001/XMLSchema#string\"\n} ],\n\"ids:constraint\" : [ {\n\"@type\" : \"ids:Constraint\",\n\"@id\" : \"https://w3id.org/idsa/autogen/constraint/43dc89ba-a953-450c-90df-36fbf1f99dd1\",\n \"ids:leftOperand\" : {\n\"@id\" : \"https://w3id.org/idsa/code/COUNT\"\n},\n \"ids:rightOperand\" : {\n\"@value\" : \"5\",\n\"@type\" : \"xsd:double\"\n},\n \"ids:operator\" : {\n\"@id\" : \"https://w3id.org/idsa/code/LTEQ\"\n}\n }\n],\n \"ids:action\" : [\n {\n \"@id\" : \"https://w3id.org/idsa/code/USE\"\n}\n]\n}",
  "additional": {},
  "_links": {
    "self": {
      "href": "https://localhost:7080/api/rules/dfe61cb7-e337-44b3-bb83-a828238198d7"
    },
    "contracts": {
      "href": "https://localhost:7080/api/rules/dfe61cb7-e337-44b3-bb83-a828238198d7/contracts{?page,size}",
      "templated": true
    }
  }
}
```

When I perform the negotiation between connectors it gives me the following error:
```
{
    "details": {
        "reason": {
            "properties": null,
            "@id": "https://w3id.org/idsa/code/MALFORMED_MESSAGE"
        },
        "payload": "Contract rejected.",
        "type": "de.fraunhofer.iais.eis.ContractRejectionMessageImpl"
    },
    "message": "Received unexpected response message."
}
```
When I look at the DSC logs it gives:
For DSC acting as provider:
```
2022-02-07T11:17:30,436 [https-jsse-nio-7080-exec-6] INFO - Received incoming message.
2022-02-07T11:17:30,438 [https-jsse-nio-7080-exec-6] INFO - Successfully validated infomodel compability.
2022-02-07T11:17:30,444 [https-jsse-nio-7080-exec-6] INFO - Requesting public key of token issuer. [url=(https://omejdn/.well-known/jwks.json), kid=(default)]
2022-02-07T11:17:30,471 [https-jsse-nio-7080-exec-6] INFO - Successfully verified DAT claims.
2022-02-07T11:17:30,497 [https-jsse-nio-7080-exec-6] INFO - Using cached DAPS DAT. [expiration=(2022-02-07T11:31:14.000+0000)]
2022-02-07T11:17:30,518 [https-jsse-nio-7080-exec-6] INFO - Sending response with status OK (200).
```
And for DSC acting as consumer:
```
2022-02-07T11:17:30,382 [https-jsse-nio-7081-exec-7] INFO - Using cached DAPS DAT. [expiration=(2022-02-07T11:31:13.000+0000)]
2022-02-07T11:17:30,391 [https-jsse-nio-7081-exec-7] INFO - Using cached DAPS DAT. [expiration=(2022-02-07T11:31:13.000+0000)]
2022-02-07T11:17:30,411 [https-jsse-nio-7081-exec-7] INFO - Sending request to https://connectora:7080/api/ids/data ...
2022-02-07T11:17:30,521 [https-jsse-nio-7081-exec-7] INFO - Successfully received response to request.
2022-02-07T11:17:30,551 [https-jsse-nio-7081-exec-7] INFO - Successfully passed SHACL-Validation.
```

This is the contract POST /api/ids/contract request body I have used:
```
[ {
        "@type" : "ids:Permission",
        "@id" : "https://connectora:7080/api/rules/dfe61cb7-e337-44b3-bb83-a828238198d7",
        "ids:description" : [ {
          "@value" : "n-times-usage",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:title" : [ {
          "@value" : "Example Usage Policy",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:action" : [ {
          "@id" : "https://w3id.org/idsa/code/USE"
        }],
        "ids:target" : "https://connectora:7080/api/artifacts/ce5aea8b-33b5-4811-a1a9-64e38c16d36e"
} ]
```

**Comment by SebastianOpriel** [comment]
@jfernandezsqs and me figured out, that the contract request body contained a non-sufficient payload. We used the permission with proper constraint and ids:target field and it worked like a charm.
