### ISSUE TITLE
Inconsistent pom.xml in the release of version 6.5.2 

### ISSUE THREAD

**Issue by ctoscano-eu** [FraunhoferISST/DataspaceConnector#798]
The file containing the project, version 6.5.2, that we get from the 'releases' link, has not the last pom.xml file that we see in the project.

**Comment by juliapampus** [comment]
The `pom.xml` can be found in the appropriate branch (see [here](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/release/v6.5.2/pom.xml)) from which the `v6.5.2` tag has been created. The main branch contains work for v7.0.0.

**Comment by ctoscano-eu** [comment]
ok, thank you.
