### ISSUE TITLE
DSC not working for external database

### ISSUE THREAD

**Issue by jmartinezsqs** [FraunhoferISST/DataspaceConnector#803]
**Bug description**
I am trying to create an artifact from a mocked database that s running locally on my machine but when I try to download the data through the connector I receive the code 417 as shown in the image:
![image](https://user-images.githubusercontent.com/82801379/146399426-e145c2c2-8855-4e28-8007-44032cd9d98b.png)

I also tried with a resource from DWD and it works ok and can retrieve the data, I don't know what could be happening nor what the error I am getting means. I have correctly created on the provider side a complete offer (with an offer, catalog, rule, contract, artifact, and representation all linked together) and it shows the catalog in the self-description as expected.

I would like to know what the problem is and how to solve it. Let me know if you need any more information regarding this problem.

**Screenshots & Logs**
This is the artifact body post call that is working ok when I download the data:
![image](https://user-images.githubusercontent.com/82801379/146400423-ebedefea-616c-410e-989c-df961df44279.png)
This is the artifact body post call that is giving the code 417 once I try to download it:
![image](https://user-images.githubusercontent.com/82801379/146400566-4e8b2aa5-187a-4d08-9796-37d0bd829304.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.4
 - Browser Postman
 - Version (DSC) 6.2

**Comment by juliapampus** [comment]
What do the logs say when trying to access the backend URL (in debug mode)? When it works with a DWD resource, I assume that maybe the connection to your backend (mocked database) has some issues.

**Comment by jmartinezsqs** [comment]
Hello. 

I attach the log that is outputted in the terminal of the components. I haven't seen any documentation regarding any other type of logging. If there is, let me know that way I could send a complete log file.

Let me know if you need any more information

These are the logs when connecting with the DWD database which is working.
First connector (provider)
![image](https://user-images.githubusercontent.com/82801379/146553903-e4c4a72d-5edb-469f-aba0-0ff97d4b3ad2.png)
Second connector (consumer)
![image](https://user-images.githubusercontent.com/82801379/146553953-8aa68f58-acba-4bf9-a1ee-31f32f97f46a.png)


And these are the logs when trying to connect to my localhost database which isn't working.
First connector (provider)
![image](https://user-images.githubusercontent.com/82801379/146554592-c10570c0-b4a8-4b09-a7b3-dc2460150281.png)
![image](https://user-images.githubusercontent.com/82801379/146554634-929578d3-7eea-45b4-98f5-1ed943a0c65c.png)
![image](https://user-images.githubusercontent.com/82801379/146554713-54c585c5-c39f-45b7-8946-f3761452b152.png)
![image](https://user-images.githubusercontent.com/82801379/146554772-5e86c5fd-7de4-47f5-8613-1dfb0e5dc82d.png)
![image](https://user-images.githubusercontent.com/82801379/146554965-e4786138-fa13-4a08-8233-390995d56542.png)
Second connector (consumer)
![image](https://user-images.githubusercontent.com/82801379/146555097-3bb65396-f7b9-478c-992d-a030380d5eef.png)
![image](https://user-images.githubusercontent.com/82801379/146555154-a2a9ad1d-c0dd-44be-aeb3-7e87e937b254.png)

**Comment by ghost** [comment]
Question:
- Is the database deployed as a Docker container?
If yes, the database container-name has to be used as part of the accessUrl instead of 127.0.0.1 (localhost). 
If the database is running locally outside of Docker, I personally can't help, because that would require access from a Container inside the Docker environment to access the DB on the local machine outside of the Docker environment. The resource from DWD for example is an external URL, which can be accessed.

**Comment by jmartinezsqs** [comment]
it isn't, is a java server that i created hosted in the 9090 port on my machine

**Comment by jmartinezsqs** [comment]
solved issue by launching the database out of the local host.
