### ISSUE TITLE
Communication with IDS AppStore not working

### ISSUE THREAD

**Issue by rizktouma** [FraunhoferISST/DataspaceConnector#804]
**Describe the bug**
When trying to access the IDS AppStore instance deployed at Fraunhofer to test the communication with the Dataspace Connector, it seems like it has not been working for a few weeks now (https://binac.fit.fraunhofer.de).

Furthermore, the application metadata example provided in the [documentation ](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/docs/pages/communication/v6/ecosystem/appStore.md#step-4-download-ids-app) seems to be missing some key attributes, such as the registry URL and the Docker image name of the application. This is then needed by the AppController to pull the docker image and start the container using Portainer:

https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/f49188ac1b7c0d042dadd61248a91a5dcce2d434/src/main/java/io/dataspaceconnector/controller/resource/type/AppController.java#L260

Furthermore, the documentation endpoints seems to be different from the endpoints of [v2.0.0](https://github.com/International-Data-Spaces-Association/IDS-AppStore/releases/tag/v2.0.0) of the AppStore. For instance, to retrieve the app metadata there is no /api/ids/app endpoint but rather a /api/apps/{id} endpoint.

**To Reproduce**
1. Clone the repository
2. Deploy it locally
3. Try to execute the /apps/{id}/actions endpoint with the following sample metadata taken from the abovementioned documentation:

```
{
  "creationDate": "2021-09-01T09:13:43.957+0200",
  "modificationDate": "2021-09-01T09:13:43.957+0200",
  "remoteId": "https://binac.fit.fraunhofer.de/api/resources/0008e657-42f2-4227-990e-10f02fdd2134",
  "remoteAddress": "https://binac.fit.fraunhofer.de/api/resources/0008e657-42f2-4227-990e-10f02fdd2134",
  "docs": "App-related human-readable documentation.",
  "envVariables": "Env1=environmentvariable;Env2=environmentvariable2",
  "storageConfig": "/data/temp:/temp",
  "supportedPolicies": [
    "PROVIDE_ACCESS"
  ],
  "keywords": [
    "processing",
    "data",
    "fit"
  ],
  "publisher": "https://fit.fraunhofer.de",
  "sovereign": "https://fit.fraunhofer.de",
  "language": "https://w3id.org/idsa/code/EN",
  "license": "https://www.apache.org/licenses/LICENSE-2.0",
  "endpointDocumentation": "https://app.com",
  "distributionService": "https://binac.fit.fraunhofer.de",
  "runtimeEnvironment": "docker",
  "additional": {
    "ids:byteSize": "974",
    "ids:checkSum": "2905321759",
    "ids:mediaType": "",
    "ids:fileName": "",
    "ids:language": "https://w3id.org/idsa/code/EN"
  },
  "_links": {
    "self": {
      "href": "https://localhost:8080/api/apps/c18fbc6c-e09f-4ded-91a8-abbc9e147ba6"
    },
    "endpoints": {
      "href": "https://localhost:8080/api/apps/c18fbc6c-e09f-4ded-91a8-abbc9e147ba6/endpoints{?page,size}",
      "templated": true
    }
  }
}
```

**Expected behavior**
Given that the AppStore instance is offline, we have not been able to test the full flow of information. However, the expected behavior would be to download the app metadata with all the necessary attributes to execute the /apps/{id}/actions endpoint. Particularly, our doubts are the following:

* Will the AppStore instance be online again soon in order to test the communication?
* Which version of the AppStore is the instanced based on? Specifically in terms of endpoints.
* Based on the current documentation, where are the attributes related to the AppStore's docker registry (registry URL, credentials, docker image name) retrieved from? Are they returned by the AppStore with the rest of the app's metadata?

**Additional context**
We are planning to use the IDS AppStore in a research project we are currently working on in the i2CAT Foundation in Barcelona. We have already used the Trusted Connector in other projects and we are members of IDSA.

**Comment by ghost** [comment]
Referenced Issue: https://github.com/International-Data-Spaces-Association/IDS-AppStore/issues/44
I would recommend contacting the AppStore colleagues directly if a demo setup is needed or further questions arise regarding the AppStore.

As for the additional information needed to deploy the image/app, they are provided by the AppStore in the final step in the form of a template. The template is based on a [Portainer template standard](https://github.com/portainer/templates/blob/master/templates-2.0.json). In addition, the access data to the Docker Registry is also documented there.
