### ISSUE TITLE
Proxy in config file

### ISSUE THREAD

**Issue by Apollo3zehn** [FraunhoferISST/DataspaceConnector#81]
The default `config.json` contains a proxy definition with hard-coded address http://proxy.dortmund.isst.fraunhofer.de:3128. I cannot reach this proxy and I don't think it is necessary for users outside the ISST. In fact, not being able to connect to the proxy causes issues when trying to run the connector. Would it be possible to remove the proxy definition? Or did I oversee another use case for this? Thank you :)

**Comment by juliapampus** [comment]
Hi, thanks for the comment. We decided to leave this proxy settings, as it is always easier to remove something than having issues with adding new properties to a JSON string. The only reason is to ensure an easy entrance to setting up the connector.
