### ISSUE TITLE
DSC acting as consumer does not obtain the information of all the offers linked to the catalog of the provider DSC

### ISSUE THREAD

**Issue by jfernandezsqs** [FraunhoferISST/DataspaceConnector#816]
I have deployed two Dataspace Connectors version 6.2.0 (one acting as provider and the other one acting as consumer). There is an error when the consumer request the self-description of the provider's catalog, it is not included all the offers of that catalog.
At provider side I have created a complete resource with one catalog and three offers linked to that catalog.
Instead of three offers as it is specified it is only accessed one of them.

I attach here what is obtained from the catalog when it is reach with the provider DSC.
[ProviderCatalog_offers.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7802618/ProviderCatalog_offers.docx)

When I use the DSC "consumer" to obtain the self-description of the provider and all the offers included in this catalog.
I am obtaining the following response body with just one offer (the last one detailed) included in the catalog and not the three of them. There is not included the other two offers that are linked to the catalog.
[Consumer_Description_Request_Message.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7802862/Consumer_Description_Request_Message.docx)

It should be obtained from the consumer all the offers of the provider, so that the consumer can select which offer fits better to him in order to proceed with the following negotiation steps.

**Comment by juliapampus** [comment]
> An offered resource is only complete if it contains at least one contract offer with at least one rule, and at least one representation with at least one artifact. Otherwise, it will not be listed in the IDS self-description because there is no complete data offer. In addition, it should not be missed to link a resource to a catalog.

Have you checked that all the required links have been created? The first `.docx` shows me that the entities are not linked, so they are not shown in the IDS catalog.

**Comment by jfernandezsqs** [comment]
I have re-tested the issue creating the missing link and I have checked it is working correctly.
I close the issue accordingly.
