### ISSUE TITLE
Prohibit Access usage policy error

### ISSUE THREAD

**Issue by jfernandezsqs** [FraunhoferISST/DataspaceConnector#822]
I have deployed two DSC v6.2.0 (ConnectorA acting as provider) and ConnectorB (acting as consumer) and I am doing the negotiation between them using the prohibit access usage policy.
>{
"title": "[\"Prohibit Access Usage Policy\"]",
"description": "",
"value": "{\n  \"@context\" : {\n    \"ids\" : \"https://w3id.org/idsa/core/\",\n    \"idsc\" : \"https://w3id.org/idsa/code/\"\n  },\n  \"@type\" : \"ids:Prohibition\",\n  \"@id\" : \"https://w3id.org/idsa/autogen/prohibition/4954834b-bbef-4024-879c-ba182f80fc65\",\n  \"ids:description\" : [ {\n    \"@value\" : \"prohibit-access\",\n    \"@type\" : \"http://www.w3.org/2001/XMLSchema#string\"\n  } ],\n  \"ids:title\" : [ {\n    \"@value\" : \"Example Usage Policy\",\n    \"@type\" : \"http://www.w3.org/2001/XMLSchema#string\"\n  } ],\n  \"ids:assignee\" : [ ],\n  \"ids:assigner\" : [ ],\n  \"ids:action\" : [ {\n    \"@id\" : \"https://w3id.org/idsa/code/USE\"\n  } ],\n  \"ids:constraint\" : [ ]\n}"
}

With the following steps the negotiation is working correctly and I receive a message with code 403.
POST /api/ids/contract
![image](https://user-images.githubusercontent.com/82888094/148934058-6746adb7-a6f2-431a-a397-40aec00e6a0d.png)
When I try to access data it is denied.
![image](https://user-images.githubusercontent.com/82888094/148934262-def20822-d7bc-4e35-b2e5-20c1c7ca4a57.png)
A policy restriction has been detected.

But when I try to negotiate with the provider "prohibit access rule" using the following Request body (ids:Permission)
>[ {
        "@type" : "ids:Permission",
        "@id" : "{{Provider_rule}}",
        "ids:description" : [ {
          "@value" : "prohibit-access",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:title" : [ {
          "@value" : "Example Usage Policy",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:action" : [ {
          "@id" : "https://w3id.org/idsa/code/USE"
        }],
        "ids:target" : "{{Provider_artifact}}"
} ]

![image](https://user-images.githubusercontent.com/82888094/148934968-bb601432-9a9f-47b4-893d-d7609ec77df3.png)
There seems to be an error here because I am able to obtain the provider "prohibit usage policy" data
![image](https://user-images.githubusercontent.com/82888094/148935219-a255303e-2351-4d76-bc23-902aafa36e07.png)
It is not restricting the access to data due to the detection of a policy restriction.
This is the self-description of connector A obtained from connector B
[Self-description of Connector A.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7846129/Self-description.of.Connector.A.docx)

**Comment by juliapampus** [comment]
I could reproduce the issue. Changing `ids:prohibition` to `ids:permission` should end up in an unsuccessful policy negotiation. Nevertheless, the DSC creates an agreement and the consumer can download the data.

**Comment by juliapampus** [comment]
Fixed in PR #823. Will be released with DSC 7.0.0.
