### ISSUE TITLE
Version not updated after DSC upgrade

### ISSUE THREAD

**Issue by SebastianOpriel** [FraunhoferISST/DataspaceConnector#849]
If we update a DSC we just upgrade the underlying image (e.g., 6.5.1 -> 6.5.2). We do not adjust created volumes from docker. When we start DSC 6.5.2, the version number is not been updated and still showing 6.5.1. We assume, that the flag for updating the database might be the solution here. But at time of upgrading the flag resulted in SQL errors.

**Comment by pdrd** [comment]
As a side note - the used flag is `configuration.force.reload=true` and it resulted in key constraint errors due to already existing ids in the database.
We have not yet tried DSC **v6.5.3**, as the changelog does not contain related updates.

**Comment by juliapampus** [comment]
@SebastianOpriel This will not be solved for any previous version and is no problem in v7 as configurations will not be migrated: https://international-data-spaces-association.github.io/DataspaceConnector/Deployment/DatabaseMigration. Therefore, I will close this issue. @pdrd Created a new issue from your comment.
