### ISSUE TITLE
Cannot query apps from DRM App Store

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#873]
Cannot query apps from DRM App Store. Getting the following error message:
```
2022-01-28 09:18:07,166 https-jsse-nio-8080-exec-2 WARN  io.dataspaceconnector.controller.util.ResponseUtils - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/VERSION_NOT_SUPPORTED, payload=Infomodel Version of incoming Message not supported!, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]
```
Don't know if this is a problem on my DSC 7.0.0 side or the App Store side. The DSC log does not say what versions it supports (expects) or what version the incoming message had.
FYI @kfidomski @ahemaid 

EDIT: According to my DSC 7 config I support: "ids:inboundModelVersion" : [ "4.0.0", "4.1.0", "4.1.2", "4.2.0", "4.2.1", "4.2.2", "4.2.3", "4.2.4", "4.2.5", "4.2.6", "4.2.7" ]
The DRM App Store currently sends 4.2.6

**Comment by ghost** [comment]
AppStore needs to add 4.2.7 to supported inbound model versions in configuration.

**Comment by sebplorenz** [comment]
@kfidomski @ahemaid can you fix this? Thanks.

**Comment by sebplorenz** [comment]
@tmberthold I think this is a very common issue. It would be nice if the error message would be more specific. Like: "The receiving Connector did not accept the message with Infomodel version 4.2.7 that was sent by this connector."

On the other hand, why do we get this message at all? The content of the request message is the same in Infomodel version 4.2.6 and 4.2.7. Can't we just accept the message as long as it is parsable?

**Comment by ghost** [comment]
There is a way to turn it off completely via `infomodel.compatibility.validation=false`.

Returning a RejectionMessage with more details only when the parser or the serializer itself throws an error on processing incoming message is worth considering. However, this of course then undermines the meaning of the supported hardcoded inbound- and outbound model version in the configmodel. Would then run sort of: "I don't actually support the version of the incoming message according to the inbound model version, but I'll try to deserialize it and if something goes wrong I'll report it and send a RejectionMessage". I'll note that on my list as feedback-idea.

**Comment by juliapampus** [comment]
With committ 759d7cb, I turned off the Infomodel comparison inside the DSC that was nevertheless no guaratee for compatibility as we do not get any information regarding this from the Infomodel library. Thus, in case of any further updates, you will not get this error anymore from a DSC v7.x.x. However, the current AppStore still includes this check, maybe you can create an issue in their repo @sebplorenz? I cannot transfer this issue, so I will close it as this is not a problem on our side.
