### ISSUE TITLE
"additional" Properties are not correctly sent to IDS metadata broker

### ISSUE THREAD

**Issue by syats** [FraunhoferISST/DataspaceConnector#892]
Properties that appear under the "additional" key of an offer description are not correctly converted to IDS-IM messages.  I show two different cases below, none of which is handled correctly, as well as an example of how this is not a Metadata Broker issue.

**Example 1**
This offer has the following in its description (as per DSC `/api/offers` endpoint)
```
        "additional": {
          "ids:theme": "https://my.vocabulary/themes/Enterprises",
          "ids:contentType": "https:/my.ontology/Dataset"
        }
```
If I try to push this, using the DSC `/api/ids/resource/update` endpoint, to an IDS Metadata Broker, I get an error back saying:
```
{
  "reason": {
    "properties": null,
    "@id": "https://w3id.org/idsa/code/MALFORMED_MESSAGE"
  },
  "payload": "The message could not be parsed due to an error in the message. Note that, due to being unable to parse this message, the ID of the correlating message is incorrect. Error: Failed to find matching enum value for https:/my.ontology/Dataset",
  "type": "de.fraunhofer.iais.eis.RejectionMessageImpl"
}
```
A message is shown in the metadata broker logs regarding enums also:
```
broker    | 18:24:27.312 [http-nio-8080-exec-4] INFO  de.fraunhofer.iais.eis.ids.jsonld.Parser - Available enums are: https://w3id.org/idsa/code/INTERFACE_DEFINITION
broker    | 18:24:27.313 [http-nio-8080-exec-4] INFO  de.fraunhofer.iais.eis.ids.jsonld.Parser - Available enums are: https://w3id.org/idsa/code/SCHEMA_DEFINITION

```

**Example 2**
This offer has the following in its description (see the lack of prefix)
```
        "additional": {
          "theme": "https://my.vocabulary/themes/Enterprises",
          "contentType": "https:/my.ontology/Dataset"
        }
```
Pushing this to the broker returns in a nice 200 message, however, when retrieving the description of the resource using the `/api/ids/description` endpoint of the DSC, I get no reference of the two additional properties quoted above:

```
{
  "@graph" : [ {
    "@id" : "http://central-core:8282/connectors/1012493422/-336692087/-1247151697",
    "@type" : "ids:Resource",
    "sameAs" : "http://localhost:8282/api/offers/5d877ea1-21a3-45b0-a9d3-8758eeac6fa4",
    "contractOffer" : "http://central-core:8282/connectors/1012493422/-336692087/-1247151697/411470713",
    "created" : "2022-02-05T16:34:13.491Z",
    "description" : "",
    "language" : "https://w3id.org/idsa/code/EN",
    "modified" : "2022-02-05T18:07:32.247Z",
    "representation" : "http://central-core:8282/connectors/1012493422/-336692087/-1247151697/-823090980",
    "resourceEndpoint" : "http://central-core:8282/connectors/1012493422/-336692087/-1247151697/-1014866500",
    "standardLicense" : "http://www.opendefinition.org/licenses/gfdl",
    "title" : "Dataset Eleven",
    "version" : "3"
  }
.
.
.


```

**Example 3**
This time I have hand crafted a message to the dataspace broker with the following payload (from their documentation)
```
{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
      "@type" : "ids:DataResource",
      "@id" : "https://w3id.org/idsa/autogen/dataResource/afaafe22-fb63-4532-a1e1-15230cb99444",
       "ids:thema": "https://my.vocabulary/themes/Industry",
      "ids:representation" : [ {
        "@type" : "ids:DataRepresentation",
        "@id" : "https://w3id.org/idsa/autogen/dataRepresentation/d5b72746-2302-4685-99b8-fc2be06fd23f",
        "ids:instance" : [ {
          "@type" : "ids:Artifact",
          "@id" : "https://broker.ids.isst.fraunhofer.de/connectors/"
        } ]
      } ]
}
```
And, when I then use the `/api/ids/description` endpoint of the DSC to get that dataset's description, I get back:
```

  "@graph" : [ {
    "@id" : "http://central-core:8282/connectors/1012493422/-336692087/1870145456",
    "@type" : "ids:DataResource",
    "sameAs" : "https://w3id.org/idsa/autogen/dataResource/afaafe22-fb63-4532-a1e1-15230cb99444",
    "representation" : "http://central-core:8282/connectors/1012493422/-336692087/1870145456/1691410900",
    "thema" : "https://my.vocabulary/themes/Industry"
  }, {
    "@id" : "http://central-core:8282/connectors/1012493422/-336692087/1870145456/1691410900",
    "@type" : "ids:DataRepresentation",
.
.
.
```

**To Reproduce**
Create an offer that has additional properties. These are created, afaiu, by adding arbitrary key-value pairs to the json.

**Expected behavior**
The additional properties should be sent in the IDS message as properties of the ids:resource (not clear how they are being sent at the moment)

**Desktop (please complete the following information):**
DSC 6.2
Changelog does not suggest this behaviour to have changed in 7.

**Comment by juliapampus** [comment]
Let me try to explain the 3 observations you made. I guess all of dem are related to the IDS Broker implementation, so I cannot ensure that my answer is correct.

### Example 1
The `properties` attribute of each class is for custom values. With the prefix `ids`, the Broker resp. the IDS Infomodel Serializer, recognizes a field that is apparently known (as part of the default IDS Infomodel). As there is a list of allowed values for `ids:theme` and `ids:contentType` and your values do not match them, this error is thrown.

### Example 2
I just checked whether additional attributes are correctly mapped to the IDS Infomodel by the DSC. They are. 
`POST /api/offers/` with payload `{"title": "Example resource", "paymentModality": "free", "test": "value"}` returns:
```
{
	"creationDate": "2022-02-07T09:51:29.938+0100",
	"modificationDate": "2022-02-07T09:51:29.938+0100",
	"title": "Example resource",
	"description": "",
	"keywords": [
		"DSC"
	],
	"publisher": "",
	"language": "",
	"license": "",
	"version": 1,
	"sovereign": "",
	"endpointDocumentation": "",
	"paymentModality": "free",
	"samples": [
	],
	"additional": {
		"test": "value"
	},
	"_links": {
		"self": {
			"href": "https://localhost:8080/api/offers/ef7e0a36-6886-489c-8afb-c9226a490f2b"
		},
		[...]
	}
}
```
as IDS:
```
{
  "@context": {
    "ids": "https://w3id.org/idsa/core/",
    "idsc": "https://w3id.org/idsa/code/"
  },
  "@type": "ids:ResourceCatalog",
  "@id": "https://localhost:8080/api/catalogs/cbd3f799-0100-43f4-af37-111d1117ccfb",
  "ids:offeredResource": [
    {
      "@type": "ids:Resource",
      "@id": "https://localhost:8080/api/offers/ef7e0a36-6886-489c-8afb-c9226a490f2b",
      "ids:language": [
        {
          "@id": "https://w3id.org/idsa/code/EN"
        }
      ],
      "ids:version": "1",
      "ids:description": [
        {
          "@value": "",
          "@language": "EN"
        }
      ],
      "ids:title": [
        {
          "@value": "Example resource",
          "@language": "EN"
        }
      ],
      [...]
      "ids:paymentModality": {
        "@id": "https://w3id.org/idsa/code/FREE"
      },
      "ids:publisher": {
        "@id": ""
      },
      "ids:sovereign": {
        "@id": ""
      },
      "ids:modified": {
        "@value": "2022-02-07T08:51:29.938Z",
        "@type": "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
      },
      "ids:resourceEndpoint": [
        {
          "@type": "ids:ConnectorEndpoint",
          "@id": "https://w3id.org/idsa/autogen/connectorEndpoint/75b5f086-fa3f-4309-8ed0-a98c915c2810",
          "ids:endpointDocumentation": [
            {
              "@id": ""
            }
          ],
          "ids:accessURL": {
            "@id": "https://localhost:8080/api/offers/ef7e0a36-6886-489c-8afb-c9226a490f2b"
          }
        }
      ],
      "test": "value"
    }
  ]
}
```
Thus, I assume that the IDS Broker somehow throws away these additional properties. Can you please take a look or comment? @sebbader @NehaThawani44 

### Example 3
I don't understand your point here. Is there some information missing or do you wonder about the syntax of the response? This is somehow different from the one used in the DSC, but still syntactically correct IDS Infomodel. I don't know the Broker's implementation, so maybe you can help here as well? @NehaThawani44 @sebbader

**Comment by syats** [comment]
Thanks @juliapampus  for the detailed reply. 

I confirm that if I add properties which are not part of IDS-IM they are correctly transmitted to the Broker, and further stored and returned by it.
