### ISSUE TITLE
DSC 7.0.0  IDS multipart messages version not supported for App Store

### ISSUE THREAD

**Issue by jfernandezsqs** [FraunhoferISST/DataspaceConnector#901]
I have deployed DSC version 7.0.0 and when I execute at the Swagger UI
POST /api/ids/description using the IDS multipart messages at https://binac.fit.fraunhofer.de/api/ids/data as detailed in the documentation (https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/IdsEcosystem/AppStore#ids-app-store)
It gives an error indicating version not supported.
![image](https://user-images.githubusercontent.com/82888094/152820057-26b5a917-cf3e-434e-8dcd-3bccf621c6d9.png)
![image](https://user-images.githubusercontent.com/82888094/152820108-e4e19826-3aad-475d-8a25-2cb0b2c7e240.png)

**Comment by HeinrichPet** [comment]
See: https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/873

**Comment by juliapampus** [comment]
For clarification: This response that you get back is no information of your running DSC, but a cleaned response from the component you are connecting to. So if there is a message, that a version is not supported, this comes from the other component.  I would therefore kindly ask you to only raise an issue at their repository.

**Comment by jfernandezsqs** [comment]
Okay perfect, I have raised an issue at their repository.
