### ISSUE TITLE
Error at Usage Notification Policy

### ISSUE THREAD

**Issue by jmartinezsqs** [FraunhoferISST/DataspaceConnector#919]
I have deployed two Dataspace connectors version 7.0.1 and configured them to be able to communicate.
They are deployed in ports 7080 (provider) & 7081 (consumer)
I create a rule on the provider with the usage notification policy with the URL of the connector I want to notify: 
![image](https://user-images.githubusercontent.com/82801379/154671506-8c15eee2-bd4f-4bab-a859-98c49f0996a4.png)
Then link this rule to an active artifact and do all the negotiation processes on the consumer side. But when I consume the data I cannot find any type of notification message.

The ID of both connectors is:
![image](https://user-images.githubusercontent.com/82801379/154671765-e8144a9e-f18c-47a7-be9d-40d3701105e1.png)
![image](https://user-images.githubusercontent.com/82801379/154671855-48d29173-6cf6-4329-8338-7999f2bdf3ef.png)

I don't know if the process is not done right or that I don't know where it should be notified, but as it is right now I cannot validate that the policy is working as expected.

Apart from the previous problem, it would be much appreciated to have a more in-depth explanation of both what the policies are meant to control as well as how can they be implemented for a specific artifact.

Thanks for the help, hope to hear from you soon and don't hesitate to ask for more information if needed.

**Comment by jmartinezsqs** [comment]
After the meeting with Sebastian Opriel, I have seen the usage policy in action and working with the URL "https://webhook.site/62e7f1b4-da2d-4c92-8a36-da253ba6af1a" which was taken from the webhook.site in the unique URL that it gives.
The only doubt left is if it would be possible to use this policy to notify one dataspace connector as it is exampled in the documentation (https://international-data-spaces-association.github.io/DataspaceConnector/Documentation/v6/UsageControl#usage-notification)

**Comment by juliapampus** [comment]
As a provider, you add your address here, so a consumer can send a message to this address on a data access.

```
"ids:rightOperand" : {
        "@value" : "https://data-provider.de/api/ids/data",
        "@type" : "http://www.w3.org/2001/XMLSchema#anyURI"
      },
```
Applying this policy, the DSC sends an `ids:NotificationMessage` on data access. The DSC also implements handlers to handle incoming NotificationMessages (`io.dataspaceconnector.service.message.handler.type.NotificationMessageHandler` and `notification-handler.xml`). There, it is implemented that the DSC responds with an `ids:MessageProcessedNotificationMessage`. Debugging in `NotificationMessageHandler` and `NotificationService` tells me that the message was sucessfully processed. There is no further message handling.
